const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const store = {
  get(k, fallback){ try { const v = localStorage.getItem(k); return v ? JSON.parse(v) : fallback; } catch { return fallback; } },
  set(k, v){ try { localStorage.setItem(k, JSON.stringify(v)); } catch {} }
};
const setup=$('#setup'), roomScreen=$('#roomScreen'), closeScreen=$('#closeScreen'), panel=$('#panel');
const personaInput=$('#personaName'), speech=$('#speech'), character=$('#character'), characterImg=$('#characterImg');
const closeImg=$('#closeImg'), closeLine=$('#closeLine'), toast=$('#toast');
let persona=store.get('gm_persona',''), visitCount=store.get('gm_visits',0), petCount=store.get('gm_pet_count',0), lastVisit=store.get('gm_last_visit',null);
let speechTimer=null, moveTimer=null, currentZone='floor', panelName=null;
const zones={desk:{left:52,top:60,state:'작업대에서 부품을 만지는 중',img:'assets/geonmyeong/sit.svg'},window:{left:31,top:55,state:'창밖을 잠깐 보는 중',img:'assets/geonmyeong/idle.svg'},floor:{left:53,top:68,state:'바닥에 주저앉아 쉬는 중',img:'assets/geonmyeong/sit.svg'},center:{left:50,top:64,state:'별일 없이 빈둥거리는 중',img:'assets/geonmyeong/idle.svg'}};
const talks={neutral:['뭐 만들지.','방금 좋은 생각 났는데… 귀찮아서 안 할래요.','이 부품 어디다 뒀더라. 아. 손에 있네.','조용하니까 좋네요. 너무 조용한가?','완벽한 기계는 재미없어요. 고칠 게 없잖아.'],late:['아직 안 자요? 전 원래 이 시간에도 멀쩡한데.','이 시간에 들어오는 사람치고 멀쩡한 사람 별로 없던데요.','졸리면 자요. 화면은 제가 보고 있을게.'],return:['살아 계셨네요. 실종 신고할 뻔했는데.','오랜만. 어디 고장 난 줄 알았어요.','안 오길래 조용해서 좋았는데. …농담.'],call:['불렀어요?','네네, 갑니다. 성질 급하시네.','뭐예요. 심심해요?'],praise:['오. 진짜 했네? 축하할까요?','하나 끝. 생각보다 성실하시네.','됐네요. 이제 그건 안 봐도 되겠다.','잘했어요. 너무 감동하지는 말고.'],pet:['이거 서비스예요?','아, 거기. 조금만 더.','되게 자연스럽게 만지시네.','손 떼면 서운해할 것 같죠? …조금은.']};
const messagesBase=[{id:'welcome',time:'오늘 · 21:03',text:n=>`${n}. 오늘은 뭐 했어요?`},{id:'food',time:'오늘 · 18:21',text:()=>`밥은 먹었죠?`},{id:'quiet',time:'어제 · 23:17',text:()=>`…생각보다 조용하네. 바쁜가 보네요.`},{id:'cat',time:'04.10 · 20:05',text:()=>`그 아줌마네 고양이 일곱 마리 다 있더라고요. 쓸데없이 보고함.`},{id:'sleep',time:'04.09 · 02:14',text:()=>`잘 자요. …안 자려나.`}];
function rand(a){return a[Math.floor(Math.random()*a.length)]} function hour(){return new Date().getHours()} function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showToast(text){toast.textContent=text;toast.classList.remove('hidden');setTimeout(()=>toast.classList.add('hidden'),1800)}
function contextualTalk(){return (hour()>=0&&hour()<5)?rand(talks.late):rand(talks.neutral)}
function say(text,duration=3300){clearTimeout(speechTimer);speech.textContent=text;const room=$('#room');const cr=character.getBoundingClientRect(),rr=room.getBoundingClientRect();let left=cr.left-rr.left+cr.width*.17,top=cr.top-rr.top-46;speech.style.left=`${Math.max(15,Math.min(left,rr.width-245))}px`;speech.style.top=`${Math.max(110,top)}px`;speech.classList.remove('hidden');speechTimer=setTimeout(()=>speech.classList.add('hidden'),duration)}
function moveTo(name){const z=zones[name];currentZone=name;character.classList.add('walking');characterImg.src='assets/geonmyeong/walk.svg';character.style.left=z.left+'%';character.style.top=z.top+'%';$('#statusText').textContent='이동 중';setTimeout(()=>{character.classList.remove('walking');characterImg.src=z.img;$('#statusText').textContent=z.state},2100)}
function scheduleMovement(){clearTimeout(moveTimer);moveTimer=setTimeout(()=>{const names=Object.keys(zones).filter(x=>x!==currentZone);moveTo(rand(names));if(Math.random()>.42)setTimeout(()=>say(contextualTalk()),2450);scheduleMovement()},7600+Math.random()*9000)}
function updateTime(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false});$('#dateLabel').textContent=d.toLocaleDateString('ko-KR',{month:'2-digit',day:'2-digit',weekday:'short'}).replaceAll('.','').trim();$('#momentDate').textContent=d.toLocaleDateString('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',weekday:'short'}).replaceAll('.','.')}
function getMessages(){let unlocked=store.get('gm_messages',['welcome','food','quiet']);if(visitCount>=2&&!unlocked.includes('cat'))unlocked.push('cat');if(hour()<4&&!unlocked.includes('sleep'))unlocked.push('sleep');if(petCount>=5&&!unlocked.includes('pet'))unlocked.push('pet');store.set('gm_messages',unlocked);const all=[...messagesBase,{id:'pet',time:'방금',text:()=>`아까 그거. 머리 만진 거요. 싫었다는 뜻은 아니고.`}];return all.filter(m=>unlocked.includes(m.id))}
function renderMessages(){const list=$('#messageList');list.innerHTML='';const msgs=getMessages();msgs.forEach(m=>{const div=document.createElement('article');div.className='message-card';div.innerHTML=`<img src="assets/geonmyeong/profile.svg" alt="건명"><div class="message-body"><strong>건명</strong><p>${escapeHtml(m.text(persona))}</p></div><time>${escapeHtml(m.time)}</time>`;list.appendChild(div)});const seen=store.get('gm_message_seen',false);$('#messageBadge').classList.toggle('hidden',seen||msgs.length===0)}
function loadTodos(){return store.get('gm_todos',[])} function saveTodos(v){store.set('gm_todos',v);renderTodos()}
function renderTodos(){const wrap=$('#todoList');wrap.innerHTML='';const todos=loadTodos();if(!todos.length){['물 마시기','작업 1시간','원고 500자','방 정리하기'].forEach((t,i)=>{if(i<2)return;});}todos.forEach((t,i)=>{const row=document.createElement('div');row.className='todo-item'+(t.done?' done':'');row.innerHTML=`<input type="checkbox" ${t.done?'checked':''} aria-label="완료"><span>${escapeHtml(t.text)}</span><button class="delete-todo" aria-label="삭제">×</button>`;row.querySelector('input').addEventListener('change',e=>{const ts=loadTodos(),became=!ts[i].done;ts[i].done=e.target.checked;saveTodos(ts);if(became){const line=rand(talks.praise);$('#todoReaction').textContent=`“${line}”`;showToast(`건명: “${line}”`)}});row.querySelector('.delete-todo').addEventListener('click',()=>{const ts=loadTodos();ts.splice(i,1);saveTodos(ts)});wrap.appendChild(row)})}
function seedTodos(){if(!store.get('gm_todos_seeded',false)){store.set('gm_todos',[{text:'물 마시기',done:false},{text:'작업 1시간',done:true},{text:'원고 500자',done:false},{text:'방 정리하기',done:true}]);store.set('gm_todos_seeded',true)}}
function enterRoom(){setup.classList.add('hidden');roomScreen.classList.remove('hidden');persona=persona||'유진';$('#playerName').textContent=persona;visitCount++;store.set('gm_visits',visitCount);store.set('gm_last_visit',Date.now());seedTodos();renderMessages();renderTodos();updateTime();scheduleMovement();const away=lastVisit&&(Date.now()-lastVisit)>1000*60*60*24*2;setTimeout(()=>say(away?rand(talks.return):`${persona}. 왔어요?`),700)}
$('#enterBtn').addEventListener('click',()=>{const n=personaInput.value.trim();if(!n){showToast('부를 이름을 먼저 적어 주세요.');return}persona=n;store.set('gm_persona',persona);enterRoom()});personaInput.addEventListener('keydown',e=>{if(e.key==='Enter')$('#enterBtn').click()});
character.addEventListener('click',openClose);$('#callBtn').addEventListener('click',()=>{moveTo('center');setTimeout(()=>say(rand(talks.call)),2250)});$('#randomTalkBtn').addEventListener('click',()=>say(contextualTalk()));
function openClose(){closeScreen.classList.remove('hidden');closeImg.src='assets/geonmyeong/close_normal.svg';closeLine.textContent='“……왜요. 싫진 않은데.”'} $('#closeBack').addEventListener('click',()=>closeScreen.classList.add('hidden'));
let lastX=null,stroke=0;const petZone=$('#petZone');petZone.addEventListener('pointerdown',e=>{petZone.setPointerCapture(e.pointerId);lastX=e.clientX;stroke=0});petZone.addEventListener('pointermove',e=>{if(lastX===null)return;const dx=Math.abs(e.clientX-lastX);if(dx>11){stroke++;lastX=e.clientX;if(stroke%2===0)petFeedback(e.clientX,e.clientY)}});['pointerup','pointercancel'].forEach(ev=>petZone.addEventListener(ev,()=>{lastX=null;stroke=0}));
function petFeedback(x,y){petCount++;store.set('gm_pet_count',petCount);if(petCount%3===0){const line=rand(talks.pet);closeLine.textContent=`“${line}”`;closeImg.src=petCount>=12?'assets/geonmyeong/close_happy.svg':'assets/geonmyeong/close_soft.svg'}const h=document.createElement('span');h.className='heart';h.textContent='♥';const rect=$('#hearts').getBoundingClientRect();h.style.left=(x-rect.left)+'px';h.style.top=(y-rect.top)+'px';$('#hearts').appendChild(h);setTimeout(()=>h.remove(),1200);if(petCount===5)renderMessages()}
function openPanel(name){panelName=name;$('#panelTitle').textContent={listen:'LISTEN',message:'MESSAGE',todo:'WITH ME',moment:'MOMENT'}[name];['listen','message','todo','moment'].forEach(n=>$(`#${n}Panel`).classList.toggle('hidden',n!==name));panel.classList.remove('hidden');if(name==='message'){store.set('gm_message_seen',true);$('#messageBadge').classList.add('hidden');renderMessages()}if(name==='moment')updateMoment()}
$$('.rail-btn').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.panel)));$('#panelBack').addEventListener('click',()=>panel.classList.add('hidden'));
$('#todoForm').addEventListener('submit',e=>{e.preventDefault();const input=$('#todoInput'),text=input.value.trim();if(!text)return;const ts=loadTodos();ts.unshift({text,done:false});saveTodos(ts);input.value=''});
const audio=$('#audio'),play=$('#playBtn'),progress=$('#progressBar');play.addEventListener('click',async()=>{try{if(audio.paused){await audio.play();play.textContent='Ⅱ';$('#musicState').textContent='재생 중'}else{audio.pause();play.textContent='▶';$('#musicState').textContent='일시정지'}}catch{showToast('assets/audio/theme.mp3 파일을 추가해 주세요.')}});audio.addEventListener('timeupdate',()=>{if(audio.duration){progress.style.width=(audio.currentTime/audio.duration*100)+'%';$('#currentTime').textContent=formatTime(audio.currentTime);$('#duration').textContent=formatTime(audio.duration)}});audio.addEventListener('error',()=>$('#musicState').textContent='테마곡 파일 대기 중');function formatTime(v){const m=Math.floor(v/60),s=Math.floor(v%60).toString().padStart(2,'0');return `${m}:${s}`}
function updateMoment(){const d=new Date();$('#momentCaption').innerHTML=`${d.toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false})}<br>${rand(['뭔가를 조립하고 있었다.','창가에서 한참 바깥을 봤다.','바닥에 앉아 렌치를 굴리고 있었다.','잠깐, 아무것도 하지 않았다.'])}`}
$('#resetBtn').addEventListener('click',()=>{if(confirm('이 기기에 저장된 이름·메시지·체크리스트 기록을 초기화할까요?')){Object.keys(localStorage).filter(k=>k.startsWith('gm_')).forEach(k=>localStorage.removeItem(k));location.reload()}});
setInterval(updateTime,30000);updateTime();
const params=new URLSearchParams(location.search);if(params.get('demo')==='1'){persona='유진';store.set('gm_persona',persona);enterRoom();if(params.get('panel'))setTimeout(()=>openPanel(params.get('panel')),300)}else if(persona){personaInput.value=persona;enterRoom()}
