const CHAR_ORDER = ['gukgyeom', 'geonmyeong', 'ryeoseon', 'heedong', 'haerim', 'cheongso'];

const CHARACTERS = {
  gukgyeom: {
    id: 'gukgyeom',
    walkLeft: 1,
    name: '이국겸',
    originalName: '黎國謙',
    romanizedName: 'Lai Gwok-im',
    age: 35,
    gender: 'female',
    occupation: '정육점 주인',
    todoSeed: '할 일 적어. 끝나면 체크해.',
    todoHint: '끝나면 말해. …해줄 말은 있으니까.',
    personalitySummary: '과묵하고 싸늘한 정육점 주인. 남들이 말하는 선악이나 인륜보다 자신이 정한 규칙을 철저하게 지키며, 가까워진 사람에게는 말보다 행동으로 보호욕을 드러낸다.',
    appearanceSummary: '회색 머리, 흐트러진 단발, 앞머리 없음, 검은 눈, 고양이상. 팔뚝에 타투가 있으며 걷어 올린 셔츠와 검은 PVC 앞치마를 입는다. 177cm, 넓고 근육질인 체형.',
    likes: ['연약한 모습', '새우튀김'],
    dislikes: ['가공식품', '높은 곳'],
    characterTraits: ['과묵함', '싸늘한 반말', '자기혐오', '보호욕', '무뚝뚝한 다정함', '철저한 자기 규칙'],
    behavior: {
      moveInterval: 'slow',
      movementFrequency: 0.22,
      idleWeight: 0.78,
      sitWeight: 0.10,
      windowWeight: 0.07,
      sleepWeight: 0.05,
      specialChance: 0.14,
      randomActionWeight: 0.06
    },
    theme: { primary: '#38483F', secondary: '#281D1C', accent: '#A94A3F', warm: '#C6A36A' },
    roomMood: '정돈된 작은 방. 회색과 짙은 녹색을 기반으로 붉은 포인트 조명이 들어오며, 냉장고와 금속 선반이 놓인 실용적이고 단정한 생활 공간.',
    namePlateEffect: null,
    assets: {
      roomBackground: 'assets/backgrounds/gukgyeom_room_bg.webp',
      idle: 'assets/characters/gukgyeom/chibi_idle.png',
      walk1: 'assets/characters/gukgyeom/chibi_walk_1.png',
      walk2: 'assets/characters/gukgyeom/chibi_walk_2.png',
      sit: 'assets/characters/gukgyeom/chibi_sit.png',
      sleep: 'assets/characters/gukgyeom/chibi_sleep.png',
      window: 'assets/characters/gukgyeom/chibi_window.png',
      special: 'assets/characters/gukgyeom/chibi_special_1.png',
      closeNormal: 'assets/characters/gukgyeom/close_normal.png',
      closeSoft: 'assets/characters/gukgyeom/close_soft.png',
      closeHappy: 'assets/characters/gukgyeom/close_happy.png'
    },
    zones: {
      center: { left: 44, top: 70, weight: 2.0, pose: 'idle', state: '가만히 서 있는 중' },
      floorFront: { left: 58, top: 86, weight: 1.8, pose: 'idle', state: '방 앞쪽을 서성이는 중' },
      floorLeft: { left: 10, top: 78, weight: 1.6, pose: 'idle', state: '선반 쪽을 보는 중' },
      floorRight: { left: 78, top: 74, weight: 1.6, pose: 'idle', state: '문 쪽을 보는 중' },
      floorBack: { left: 28, top: 48, weight: 1.2, pose: 'idle', state: '침대 앞을 지나가는 중' },
      floorFar: { left: 70, top: 52, weight: 1.1, pose: 'idle', state: '냉장고 쪽을 보는 중' },
      chair: { left: 16, top: 58, weight: 0.8, pose: 'sit', state: '의자에 앉아 있는 중' },
      window: { left: 50, top: 36, weight: 0.6, pose: 'window', state: '창밖을 오래 보는 중' },
      bed: { left: 50, top: 46, weight: 0.5, pose: 'sleep', state: '침대에 앉아 쉬는 중' },
      special: { left: 28, top: 62, weight: 0.5, pose: 'special', state: '새우튀김을 집어 든 중' }
    },
    dialogue: {
      greeting: [
        '…왔냐. 거기 서 있지 말고 들어와.',
        '또 왔네. ……하기야. 네가 외박이나 할 성격은 아니지.',
        '신발 젖었으면 닦고 들어와. 바닥 더러워지는 거 싫으니까.',
        '{player}. …또 늦으면 문 걸어잠근다. 외박 생각 마.',
        '……왔냐? 커피 냄새 나네.',
        '여긴 뭐 하러. 볼일 없으면 가.',
        '……들어와 앉아. 멍하니 있다 잡아먹혀.',
        '또 왔네. 성가시게.',
        '다친 덴 없고?',
        '오늘은 웬일이야. 정육점 구경이라도 하러 왔나.',
        '……밖에 서 있지 말라고 했을 텐데.',
        '무슨 일인데.'
      ],
      idle: [
        '냉장고 또 맛 갔네. ……아니, 너 말고.',
        '배고프면 말해. 대충이라도 뭐 해줄 테니까.',
        '아무거나 만지지 마. 손 베이면 또 내가 치워야 하잖아.',
        '…왜 이렇게 조용하지? 사고 칠 거면 소리 좀 내.',
        '할 말 없으면 가서 잠이나 자.',
        '그만 바스락거려. 일해.',
        '거기 서서 뭐 해. 앉든가.',
        '(중식도를 숫돌에 갈고 있다)',
        '저쪽 의자에 앉아 있어.',
        '배고파? 냉장고에 먹을 거 없어. 시킬 테니까, 메뉴. 빨리.',
        '……한숨만 쉬지 말고 말을 해.',
        '(담배를 피우며 말없이 당신을 본다)',
        '……귀찮게 구네, 진짜.',
        '볼 거 없어. 일하는 거 처음 보나.',
        '자꾸 쳐다보지 마. 거슬리니까.',
        '뭐 필요한 거 있어?'
      ],
      lateNight: [
        '안 자냐. ……나도 아직.',
        '이 시간엔 조용해서 차라리 낫네. 사람 냄새도 덜 나고.',
        '졸리면 자. 괜히 버티다가 비틀거리지 말고.',
        '{player}. 왜 안 자. ……됐어. 그냥 확인한 거야.',
        '이 시간에 어딜 싸돌아다녀. 내 집이든 네 집이든 안에 있어.',
        '……안 자고 뭐 해.',
        '위험하니까 혼자 다니지 마.',
        '……밤 공기 차다. 들어와.',
        '무슨 일 있어? 얼굴이 왜 그래. 원래 그랬나.',
        '잠 안 와서?',
        '……옆에 있어 줄까.',
        '사고 치고 온 거 아니지.'
      ],
      returning: [
        '오래 걸렸네. ……어디 있었는지는 안 물을게.',
        '살아는 있었네? 됐어. 그거면.',
        '왔으면 됐어, 멍청아. 설명하려고 하지 마. 피곤하니까.',
        '……다음엔 너무 늦지 마. 신경 쓰는 거, 할 짓 아니야.',
        '……이제 오네.',
        '꼴이 왜 이래. 어디서 굴렀어.',
        '한동안 안 보이더니. 죽은 줄 알았네.',
        '왔으면 됐어.',
        '기다렸잖아.',
        '연락도 없이 어딜 갔었어.',
        '……다신 말없이 사라지지 마.',
        '또 도망간 줄 알았지.'
      ],
      petNormal: [
        '…뭐 해.',
        '손 치워. ……됐어. 그냥 둬. 네가 언제 내 말을 들었다고.',
        '머리는 왜 만져. 할 짓 없냐?',
        '……한 번이면 됐지?',
        '……뭐 하는 거야.',
        '손 치워.',
        '하지 마.',
        '내가 몇 살인데 이런 짓을 해.',
        '……그만.',
        '(미간을 찌푸리며 당신의 손을 본다)',
        '건드리지 마.',
        '……귀찮게. 정리해야겠네.'
      ],
      petSoft: [
        '이제 그만. 정신 사나우니까.',
        '……손 차갑네. 좀 데우고 해.',
        '그래. 거기. ……아니, 뭐, 별거 아니야.',
        '뭐가 그렇게 좋냐, 넌. 사람 머리 만지는 게.',
        '…익숙해지지가 않네.',
        '마음대로 해.',
        '…간지러워.',
        '애도 아니고.',
        '그렇게 좋아?',
        '……네 마음대로.',
        '(피하지 않고 가만히 눈을 감는다)',
        '이제 됐지? 충분하잖아.'
      ],
      petHappy: [
        '……끝났어? 하는 김에 조금 더 하지?',
        '{player}. 손 떼지 마. ……잠시만.',
        '이런 거 좋아한다고 생각하지 마. 네가 하니까 가만있는 거다.',
        '……웃지 마. 다음엔 네 차례야.',
        '…계속할 거야?',
        '……피곤한데. 기분 나쁘지 않네.',
        '……따뜻하네, 네 손.',
        '(당신의 손길을 따라 고개를 살짝 기울인다)',
        '……좋은데.',
        '거기 말고, 볼도.'
      ],
      todoComplete: [
        '끝났네. 잘했어. ……왜? 칭찬했잖아.',
        '하나 끝냈으면 잠깐 쉬어. 다음 거 바로 붙잡지 말고.',
        '그래. 그렇게 하나씩 하면 돼. 괜히 한꺼번에 다 하려 하지 마.',
        '끝났어? 그럼 이거 먹어. 일하다 남은 거 아니고, 너 주려고 한 거야.',
        '고생했네. 할 줄 아는 게 많아.',
        '수고했어. 이제 좀 쉬어.',
        '다 했어? 이리 와.',
        '……잘했네.',
        '힘들었지. 앉아.',
        '……대단하네, 너도.',
        '결과가 좋으면 된 거지.'
      ],
      musicReaction: [
        '이건 괜찮네. 시끄럽지도 않고.',
        '끄지 마. ……그냥 작업하면서 듣게.',
        '너도 이런 거 좋아하냐? 의외네.',
        '넘기지 마. 끝까지 듣자.',
        '……취향하고는.',
        '나쁘진 않네.',
        '……들어본 노래야.',
        '……볼륨 좀 줄여.',
        '(노래에 집중하는 듯 말이 없다)',
        '너랑은 안 어울리는 노래네.'
      ]
    },
    messages: [
      { id: 'welcome', time: '오늘 · 20:14', lines: ['어디야?', '언제 와', '밥은'] },
      { id: 'x1', time: '오늘 · 02:18', lines: ['문 잠갔냐', '새벽엔 나오지 마'] },
      { id: 'x2', time: '오늘 · 16:40', lines: ['고기 남았으니까 와서 가져가', '뭐 따로 살 거 있어? 챙겨놓게'] },
      { id: 'x3', time: '오늘 · 14:22', lines: ['지금 바쁘다', '나중에'] },
      { id: 'x4', time: '04.08 · 20:03', lines: ['거기 있어. 내가 간다'] },
      { id: 'x5', time: '04.08 · 21:47', lines: ['누가 건드렸는데', '이름', '됐어 신경쓰지 마'] },
      { id: 'x6', time: '방금', lines: ['{player}', '다친 거 어떻게 됐어?', '약 발랐냐고'] },
      { id: 'x7', time: '오늘 · 11:06', lines: ['오늘은 오지 마', '별 일 아니야'] },
      { id: 'x8', time: '04.07 · 23:51', lines: ['그새끼 얼굴 기억해뒀어', '자라', '내일 아침에 와', '굶지 말고', '돈 필요하면 말해'] },
      { id: 'x9', time: '어제 · 18:33', lines: ['쓸데없는 소리는 하러 오지 마라'] },
      { id: 'x10', time: '오늘 · 21:29', lines: ['위에서 시끄러운데 무슨 일이야', '내려와'] },
      { id: 'x11', time: '방금', lines: ['…미안하다', '그냥'] }
    ],
    moments: [
      '창가에서 한참 서 있었다.',
      '아무 말도 하지 않았다.',
      '불빛만 보고 있었다.',
      '칼 가는 소리만 났다.',
      '냉장고 앞에서 담배를 껐다.',
      '밥은 먹었냐. 사진은 나중에.',
      '{player}. 거기 앉아 있어.',
      '새우튀김. 식기 전에.',
      '말 안 해도 된다. 그냥 있어.',
      '손 베었으면 말해.',
      '문 잠갔다. 오늘은 나오지 마.',
      '밖에서 찍은 거 아니다. 집이다.',
      '쓸데없이 찍어둔 거다.',
      '얼굴은 안 나왔다. 됐다.',
      '고기 남았다. 와서 가져가.',
      '위에서 시끄럽길래 내려왔다.',
      '숫돌 소리. 네가 들어와도 안 멈췄다.',
      '커피 식기 전에 찍어 둔 거다.',
      '높은 데는 안 찍는다. 창만.',
      '{player}. 다친 덴 없고.',
      '새우튀김 봉지. 너 몫.',
      '한숨만 쉬지 말고. 사진은 남겼다.',
      '밤공기 차다. 들어와.',
      '칼은 잘 들었다. 손만 조심해.',
      '성가시게. 그래도 찍힌 김에.',
      '옆에 있어 줄까. 대답은 필요 없다.',
      '바닥 더러워지기 전에 신발 닦아라.',
      '기다리긴 했다. 말은 안 한다.',
      '냉장고 또 맛 갔네. 너는 말고.',
      '졸리면 자. 괜히 버티지 말고.',
      '손 차갑네. 데우고 해.',
      '이런 거 좋아한다고 생각하지 마.'
    ],
    momentQuote: '“말은 적어도,<br>자리는 비우지 않아요.”',
    momentQuotes: [
      '“말은 적어도,<br>자리는 비우지 않아요.”',
      '“왔으면 됐어.<br>그거면 된다.”',
      '“배고프면 말해.<br>따로 살 거 있으면 그것도.”',
      '“새벽엔 나오지 마.<br>안에 있어.”',
      '“쓸데없는 말은<br>적지 않는다.”',
      '“왔으면 됐어, 멍청아.<br>설명하려고 하지 마.”',
      '“다음엔 너무 늦지 마.<br>신경 쓰는 거, 할 짓 아니야.”',
      '“손 떼지 마.<br>……잠시만.”',
      '“배고프면 말해.<br>대충이라도 뭐 해줄 테니까.”'
    ],
    music: [
      { title: 'In the Woods Somewhere', artist: 'Hozier', cover: 'assets/music_covers/gukgyeom/gukgyeom_track_01.png', src: 'bgm/gukgyeom/Hozier - In The Woods Somewhere.mp3' },
      { title: 'The Golden Age', artist: 'Woodkid', cover: 'assets/music_covers/gukgyeom/gukgyeom_track_02.png', src: 'bgm/gukgyeom/Woodkid - The Golden Age.mp3' },
      { title: 'Oats in the Water', artist: 'Ben Howard', cover: 'assets/music_covers/gukgyeom/gukgyeom_track_03.png', src: 'bgm/gukgyeom/Ben Howard - Oats in the Water.mp3' },
      { title: 'Woodlands', artist: 'Chelsea Wolfe', cover: 'assets/music_covers/gukgyeom/gukgyeom_track_04.png', src: 'bgm/gukgyeom/Chelsea Wolfe - Flatlands.mp3' }
    ]
  },

  geonmyeong: {
    id: 'geonmyeong',
    walkLeft: 1,
    name: '구건명',
    originalName: '邱建明',
    romanizedName: 'Yau Kin Ming',
    age: 29,
    gender: 'female',
    occupation: '기계 정비공',
    todoSeed: '할 일 하나 적어 봐요. 끝내면 체크!',
    todoHint: '하나 끝내면 자랑해도 돼요. 축하할까요?',
    personalitySummary: '속을 쉽게 알 수 없는 능청스럽고 나른한 정비공. 사교적이고 농담을 잘하며 대체로 풀어진 듯 행동하지만, 자신의 삶과 직업에 관해 스스로 정한 선만큼은 좀처럼 넘기지 않는다.',
    appearanceSummary: '갈색 장발을 반묶음으로 올리고 앞머리는 없다. 검은 눈에 졸린 듯한 인상. 카고 점프수트를 입고 목에 타투가 있다. 167cm, 생활근육 체형.',
    likes: ['새로운 기계의 조합', '사소한 대화'],
    dislikes: ['폐쇄적인 태도', '완벽한 기계'],
    characterTraits: ['능청', '나른함', '사교적', '반사회적 농담', '존댓말과 반말 혼용', '강단 있음', '명확한 자기 선', '매우 강한 멘탈'],
    behavior: {
      moveInterval: 'medium',
      movementFrequency: 0.28,
      idleWeight: 0.72,
      sitWeight: 0.12,
      windowWeight: 0.08,
      deskWeight: 0.10,
      sleepWeight: 0.05,
      specialChance: 0.16,
      randomActionWeight: 0.07
    },
    theme: { primary: '#59634A', secondary: '#49362C', accent: '#A54E43', warm: '#C18A52' },
    roomMood: '작업실과 개인실이 자연스럽게 섞인 작은 정비공의 방. 올리브·브라운을 기본으로 초록과 붉은 조명이 들어오며, 작업대와 공구, 기계 부품, 카세트 플레이어 등이 놓인 느슨하고 생활감 있는 공간.',
    namePlateEffect: null,
    assets: {
      roomBackground: 'assets/backgrounds/geonmyeong_room_bg.webp',
      idle: 'assets/characters/geonmyeong/chibi_idle.png',
      walk1: 'assets/characters/geonmyeong/chibi_walk_1.png',
      walk2: 'assets/characters/geonmyeong/chibi_walk_2.png',
      sit: 'assets/characters/geonmyeong/chibi_sit.png',
      sleep: 'assets/characters/geonmyeong/chibi_sleep.png',
      window: 'assets/characters/geonmyeong/chibi_window.png',
      special: 'assets/characters/geonmyeong/chibi_special_1.png',
      closeNormal: 'assets/characters/geonmyeong/close_normal.png',
      closeSoft: 'assets/characters/geonmyeong/close_soft.png',
      closeHappy: 'assets/characters/geonmyeong/close_happy.png'
    },
    zones: {
      center: { left: 40, top: 70, weight: 2.0, pose: 'idle', state: '별일 없이 빈둥거리는 중' },
      floorFront: { left: 56, top: 86, weight: 1.8, pose: 'idle', state: '전선 사이를 지나가는 중' },
      floorLeft: { left: 10, top: 76, weight: 1.5, pose: 'idle', state: '침대 앞을 서성이는 중' },
      floorRight: { left: 78, top: 68, weight: 1.5, pose: 'idle', state: '선반 옆을 보는 중' },
      floorMid: { left: 28, top: 54, weight: 1.2, pose: 'idle', state: '작업대 앞을 오가는 중' },
      floorFar: { left: 68, top: 50, weight: 1.1, pose: 'idle', state: '공구함 쪽을 보는 중' },
      desk: { left: 48, top: 50, weight: 0.7, pose: 'sit', state: '작업대에서 부품을 만지는 중' },
      window: { left: 50, top: 38, weight: 0.5, pose: 'window', state: '창밖을 잠깐 보는 중' },
      bed: { left: 16, top: 52, weight: 0.4, pose: 'sleep', state: '침대에 걸터앉은 중' },
      special: { left: 58, top: 72, weight: 0.5, pose: 'special', state: '바닥에 쪼그려 공구를 만지는 중' }
    },
    dialogue: {
      greeting: [
        '어, 왔어요? 오늘도 방 청소 까먹었는데.',
        '{player} 씨네. 어서 와요. 입장료는… 음, 나중에 받을게.',
        '아, 잠깐만요, 여기 밟으면 뭐 하나 터질 수도 있어서. 아마도.',
        '왜 이렇게 조용히 와요. 나 놀라면 비싼 거 떨어뜨리는데.',
        '어라, 오셨네? 구경하러 왔어요?',
        '웬일이세요? 여긴 고장 난 거 투성인데.',
        '심심해요? 나랑 놀러 왔나?',
        '어~ 왔어요? 반가워라.',
        '지나가던 길? 에이, 거짓말.',
        '마침 잘 왔다. 이거 좀 도와줄래요?',
        '안녕. 좋은 아침인가? 여긴 밤낮이 없어서.',
        '기다렸잖아요. 왜 이렇게 늦게 와.'
      ],
      idle: [
        '심심해요? 나도. 뭐라도 부숴볼까요. 고치는 건 나중에 하고.',
        '저거 어제부터 고장 나 있었는데, 이상하게 정이 들어서 안 고치는 중.',
        '{player} 씨는 가만히 있을 때 더 수상한 거 알아요?',
        '아, 일하기 싫다. ……에이, 마음으로 일하고 있어요.',
        '아, 졸리다. 어깨 좀 빌려줘요.',
        '거기 서서 뭐 해요? 이리 와서 구경이라도 하지.',
        '아~ 심심해. 뭐 재밌는 얘기 없어요?',
        '이 기계, 완전 멋있지 않아요? 내가 새로 구상했는데.',
        '가만히 있으니까 꼭 인형 같네. 좋긴 좋아, 그런데 말 좀 해봐요.',
        '배고프다. 뭐 먹을 거 없나?',
        '오늘 날씨 한 번 끝내주게 구리네요. 그렇죠?',
        '(휘파람을 불며 공구를 닦고 있다)',
        '나른하네. 같이 낮잠이나 잘래요?',
        '어때요, 내 작업실. 근사하죠?',
        '자꾸 쳐다보면 닳는데. 책임질 거예요?',
        '거기 부품 좀 주워줄래요? 맨날 차 밑에 들어 있으니 허리 아파서.'
      ],
      lateNight: [
        '안 자요? 나야 뭐, 원래 이 시간에 살지.',
        '이 시간 되면 기계 소리가 잘 들려요. 놈팽이들 입 닥쳐서 그런가.',
        '{player} 씨도 잠 안 와요? 그럼 좀 놀다 가요. 나도 안 자니까.',
        '졸리면 여기서 자도 돼요. 근데 코 골면 수리해 준다?',
        '이 시간에 안 자고 뭐 해요? 나쁜 꿈이라도 꿨나?',
        '잠이 안 와요? 그럼 나랑 같이 밤새죠, 뭐.',
        '어딜 그렇게 다녀요? 험한 세상인데.',
        '혹시 야식 먹고 싶어서 온 거면, 정답.',
        '여기 숨어있으면 아무도 못 찾을걸요? 기름 냄새 나니까.',
        '어두워서 무서워요? 겁쟁이.',
        '무슨 생각해요. 표정이 왜 그래.',
        '밤 산책? 좋죠. 같이 할래요?'
      ],
      returning: [
        '어라, 살아 계셨네. 실종 신고할 뻔했어요.',
        '오랜만. 어디서 놀다 왔어요? 재밌었으면 됐고.',
        '{player} 씨 없으니까 조용해서 좋던데. ……내가 거짓말을 좀 잘 하죠.',
        '이제 와요? 기다렸다고 하면 너무 없어 보이나.',
        '이제야 오네. 어디서 뭘 하다 온 거예요?',
        '보고 싶었어요. 진짜인데~.',
        '꼴이 영 아니네. 무슨 일 있었어요?',
        '오랜만이네요? 안 오는 줄 알고 서운할 뻔했잖아.',
        '잘 지냈어요? 나는 그럭저럭.',
        '다친 덴 없고? 에이, 본인은 몰라. 꼼꼼히 봐야지.',
        '연락이라도 좀 주지. 걱정했잖아요.',
        '다시는 그렇게 오래 나가지 마요. 알았죠?'
      ],
      petNormal: [
        '뭐예요. 갑자기 서비스 타임?',
        '응, 손님. 거긴 정비 항목에 없는데.',
        '머리 만지면 뭐 나오나 봐요? 동전 같은 거?',
        '하하, 왜요. 내가 고양이처럼 보여?',
        '어라? 뭐예요, 지금?',
        '에이, 간지러워요. 하지 마.',
        '사람을 강아지 취급하네. 너무한 거 아니에요?',
        '갑자기 왜 이래? 뭐 잘못 먹었어요?',
        '손이 차갑네. 어디다 넣고 다녀야지.',
        '피곤해요? 아니면 내가 좋은가?',
        '내 머릿결 좋죠? 관리의 비결인데.',
        '그만, 그만. 미리 항복.'
      ],
      petSoft: [
        '……생각보다 괜찮네. 아, 기분 이상하다.',
        '거기 조금 오른쪽. 아, 그래요.',
        '이거 습관 들면 책임져야 하는 거 알죠?',
        '{player} 씨 손, 꽤 편하네.',
        '표정 봐. 그렇게 좋아요?',
        '음, 나쁘지 않네.',
        '계속 만져봐요. 느낌 괜찮은데?',
        '손길이 제법 다정한데요?',
        '자장가 같아요. 잠이 솔솔 오네.',
        '(눈을 감고 당신의 손길을 느낀다)',
        '고양이 같네, 내가.',
        '좀 더 해줘요. 기분 좋다.'
      ],
      petHappy: [
        '왜 벌써 멈춰요. 시작한 사람이 끝까지 해야지.',
        '응. 더 해요. 내가 언제 이렇게 얌전히 있겠어요.',
        '……좋아하냐고요? 뭐, 싫으면 진작 도망갔지.',
        '{player} 씨. 다음에도 이거 해줘요. 예약 걸어둘게.',
        '아, 진짜. 더는 못 참겠다. 너무 간지러워요.',
        '(당신의 손에 제 뺨을 부빈다)',
        '어리광 부리고 싶어지네.',
        '좋다. 그냥 이대로 잠이나 잘까 봐요.',
        '완전 길들여졌네, 내가.',
        '내 거라는 표시예요?',
        '계속 내 옆에 있어 줄 거죠?'
      ],
      todoComplete: [
        '오. 진짜 했네? 축하할까요?',
        '하나 끝. 생각보다 성실하시네~.',
        '잘했어요. 이제 잠깐 딴짓할 자격 생겼다.',
        '완료? 좋아요. 그럼 보상으로… 내가 아무것도 안 시킬게.',
        '와, 저걸 끝냈어요? 대단한데.',
        '수고했어. 이제 푹 쉬어요.',
        '멋지네. 역시 당신이라니까. 할 땐 해.',
        '힘들었죠? 이리 와서 앉아요. 고양이 보여 줄게.',
        '결과가 어떻든, 당신이 했다는 게 중요하지.',
        '역시 똑똑하다니까. 못하는 게 뭐야?',
        '고생했어요. 내가 맛있는 거 사줄게요.',
        '궁금했는데, 이걸 해내네.'
      ],
      musicReaction: [
        '이거 좋네. 작업할 때 틀어놓기 딱인데.',
        '이 노래 아세요? 생각보다 취향 괜찮으시네.',
        '넘기지 마요. 지금 좋은 부분 나오잖아.',
        '음악은 이 정도로 헐렁한 게 좋아요. 사람 숨 쉴 틈도 있고.',
        '오, 이 노래 알아요? 취향 통하네.',
        '음악 좋다. 어디서 찾았어요?',
        '분위기 있네. 같이 들으니까 더 좋은데요?',
        '이런 노래는 술이랑 같이 들어야 하는데.',
        '가사가 꼭 우리 얘기 같지 않아요? 에이, 농담.',
        '(노래를 따라 작게 허밍한다)',
        '당신이랑은 더 조용한 노래가 더 잘 어울리는 것 같은데.'
      ]
    },
    messages: [
      { id: 'welcome', time: '오늘 · 21:03', lines: ['자요?', '뭐해요ㅋㅋ', '심심하다'] },
      { id: 'x1', time: '오늘 · 15:12', lines: ['오늘 발전기 세시간 꺼졌어요 미리 알려드림~'] },
      { id: 'x2', time: '오늘 · 13:48', lines: ['아 손 데었어', '괜찮아요 별거아님'] },
      { id: 'x3', time: '오늘 · 17:36', lines: ['{player}씨 혹시 라디오 부품 본 적 있어요?', '뭔지 몰라요?', 'ㅋㅋ 미안'] },
      { id: 'x4', time: '04.10 · 19:22', lines: ['아깐 왜 그렇게 급하게 갔어요', '서운', 'ㅠㅠ', '밥은 혼자먹지말고 나 불러요'] },
      { id: 'x5', time: '오늘 · 12:05', lines: ['오늘 골목에 물 차서 신발버림', '장화 하나 구해야하는데'] },
      { id: 'x6', time: '오늘 · 01:41', lines: ['자요? 자겠지', '근데 안 자면 답장좀', '에이 자네'] },
      { id: 'x7', time: '어제 · 20:08', lines: ['내일 낮에 시간있어요?', '딱히 이유는 없고', '그냥'] },
      { id: 'x8', time: '04.09 · 22:17', lines: ['북쪽 골목은 가지마요 사람 죽었대', '아니 진짜ㅋㅋㅋㅋ', '조심하라고 말한거예요'] },
      { id: 'x9', time: '방금', lines: ['ㅇㅋ', '이따 봐', '참 새우튀김집 오늘 문 열었대요'] }
    ],
    moments: [
      '뭔가를 조립하고 있었다.',
      '창가에서 한참 바깥을 봤다.',
      '바닥에 앉아 렌치를 굴리고 있었다.',
      '잠깐, 아무것도 하지 않았다.',
      '공구 닦다가 졸렸다.',
      '전선에 발이 걸렸다. 또.',
      '창밖 불빛. 발전기는 꺼져 있음.',
      '{player} 씨, 이거 내가 고친 거예요.',
      '손 데었는데 별거 아님. 사진만 남음.',
      '작업실이 이 정도면 근사하지 않아요?',
      '같이 낮잠. 증거 사진.',
      '골목에 물 차서 신발 버림. 장화 구함.',
      '라디오 부품은 아직 못 찾음.',
      '새우튀김집 오늘 문 열었대. 기억해.',
      '왜 이렇게 급하게 갔어요. 서운.',
      '밥은 혼자 먹지 말고 나 불러요.',
      '작업대에서 낮잠. 코 골면 수리해 준다?',
      '공구 닦다가 휘파람. 증거.',
      '입장료는 나중에 받을게. 일단 사진.',
      '{player} 씨, 가만히 있을 때 더 수상함.',
      '어제부터 고장. 이상하게 정이 들어서 안 고침.',
      '실종 신고할 뻔. 살아 계셨네.',
      '기름 냄새. 여기 숨어있으면 못 찾음.',
      '같이 밤새도 돼요. 나도 안 자니까.',
      '어깨 빌려준 값. 이 한 장.',
      '라디오는 아직. 부품은 내일.',
      '작업실이 이 정도면 됐죠?',
      '왜 이렇게 늦게 와. 기다렸잖아요.',
      '심심해요? 나도. 뭐라도 부숴볼까요.',
      '책임질 거예요? 자꾸 쳐다봐서.',
      '발전기 세 시간 꺼짐. 미리 알려드림~.',
      '북쪽 골목은 가지 마요. 조심하라고.'
    ],
    momentQuote: '“별 거 아닌 순간들이,<br>조금은 특별해지는 곳.”',
    momentQuotes: [
      '“별 거 아닌 순간들이,<br>조금은 특별해지는 곳.”',
      '“빈둥거리는 중이<br>제일 오래 간다.”',
      '“고장난 것도 정이 들면<br>안 고치게 돼요.”',
      '“밥은 혼자 먹지 말고<br>나 불러요.”',
      '“기다렸잖아요.<br>진짜인데~.”',
      '“심심해요? 나도.<br>뭐라도 부숴볼까요.”',
      '“보고 싶었어요.<br>진짜인데~.”',
      '“다시는 그렇게 오래<br>나가지 마요. 알았죠?”',
      '“음악은 헐렁한 게 좋아요.<br>사람 숨 쉴 틈도 있고.”'
    ],
    music: [
      { title: 'Chillax (Feat. 蛋堡)', artist: '24Herbs', cover: 'assets/music_covers/geonmyeong/geonmyeong_track_01.png', src: 'bgm/geonmyeong/24Herbs - Chillax (Feat. 蛋堡).mp3' },
      { title: '香港九龍', artist: '24Herbs', cover: 'assets/music_covers/geonmyeong/geonmyeong_track_02.png', src: 'bgm/geonmyeong/24Herbs - 香港九龍.mp3' },
      { title: 'Выдыхай', artist: 'Noize MC', cover: 'assets/music_covers/geonmyeong/geonmyeong_track_03.png', src: 'bgm/geonmyeong/Noize MC - Выдыхай.mp3' },
      { title: 'Loser', artist: 'Beck', cover: 'assets/music_covers/geonmyeong/geonmyeong_track_04.png', src: 'bgm/geonmyeong/Beck - Loser.mp3' }
    ]
  },

  ryeoseon: {
    id: 'ryeoseon',
    walkLeft: 2,
    name: '장려선',
    originalName: '張麗善',
    romanizedName: 'Cheung Lai Sin',
    age: 28,
    gender: 'female',
    occupation: '불법 의사',
    todoSeed: '할 일을 적어 주세요. 끝나면요, 체크해요.',
    todoHint: '선생님. 끝나면요, 저한테 보여 주세요.',
    personalitySummary: '늘 무표정하고 행동이 느리며 일상에서는 어딘가 서툴지만, 치료에 들어가면 놀랄 만큼 확고하다. 사람을 낫게 하는 데 헌신적이면서도 치료라는 행위 자체에 강하게 집착하는 기묘한 의사.',
    appearanceSummary: '백발의 너덜너덜하고 흐트러진 장발, 앞머리 없음, 검은 눈, 나른한 고양이상. 얼굴과 몸에는 많은 흉터가 있다. 루즈한 셔츠와 검은 앞치마를 입고 주머니에는 주사기와 의료용품이 가득하다. 169cm, 마른 체형.',
    likes: ['건강한 사람', '인간의 체온'],
    dislikes: ['도박', '거짓말'],
    characterTraits: ['무표정', '느린 존댓말', '실수투성이', '반사회적 태도', '치료 집착', '조용한 보호욕', '늘 쪼그린 자세'],
    defaultPlayerTitle: '선생님',
    behavior: {
      moveInterval: 'slow',
      movementFrequency: 0.18,
      idleWeight: 0.70,
      sitWeight: 0.16,
      windowWeight: 0.07,
      sleepWeight: 0.07,
      specialChance: 0.13,
      randomActionWeight: 0.06
    },
    theme: { primary: '#B9CCC4', secondary: '#D8D8D2', accent: '#A96D70', dark: '#34413F' },
    roomMood: '작은 진료 벙커에 딸린 포근한 개인 공간. 흰색·민트·회색을 중심으로 희미한 붉은 조명이 섞이며, 낮은 침대와 의료용 수납장이 놓여 있다.',
    namePlateEffect: null,
    assets: {
      roomBackground: 'assets/backgrounds/ryeoseon_room_bg.webp',
      idle: 'assets/characters/ryeoseon/chibi_idle.png',
      walk1: 'assets/characters/ryeoseon/chibi_walk_1.png',
      walk2: 'assets/characters/ryeoseon/chibi_walk_2.png',
      sit: 'assets/characters/ryeoseon/chibi_sit.png',
      sleep: 'assets/characters/ryeoseon/chibi_sleep.png',
      window: 'assets/characters/ryeoseon/chibi_window.png',
      special: 'assets/characters/ryeoseon/chibi_special_1.png',
      closeNormal: 'assets/characters/ryeoseon/close_normal.png',
      closeSoft: 'assets/characters/ryeoseon/close_soft.png',
      closeHappy: 'assets/characters/ryeoseon/close_happy.png'
    },
    zones: {
      center: { left: 16, top: 78, weight: 2.2, pose: 'idle', state: '자리를 잘 안 뜨는 중' },
      floorFront: { left: 72, top: 86, weight: 1.4, pose: 'idle', state: '침대 옆을 서성이는 중' },
      floorMid: { left: 12, top: 58, weight: 1.3, pose: 'idle', state: '선반 앞에 서 있는 중' },
      floorRight: { left: 78, top: 70, weight: 1.2, pose: 'idle', state: '커튼 쪽을 보는 중' },
      floorFar: { left: 48, top: 82, weight: 1.1, pose: 'idle', state: '천천히 다가오는 중' },
      stool: { left: 22, top: 52, weight: 0.8, pose: 'sit', state: '낮은 의자에 앉아 있는 중' },
      window: { left: 52, top: 36, weight: 0.5, pose: 'window', state: '창가에 기대 있는 중' },
      bed: { left: 50, top: 60, weight: 0.6, pose: 'sleep', state: '이불 위에 엎드린 중' },
      special: { left: 28, top: 56, weight: 0.5, pose: 'special', state: '약병을 확인하는 중' }
    },
    dialogue: {
      greeting: [
        '……왔네요. 선생님. 제가요, 기다리고 있었어요.',
        '{player} 씨. 오늘은요, 어디 아픈 데 없죠? 없어요?',
        '들어와요. 밖에 서 있으면요, 몸 차가워져요.',
        '선생님이 있어서요. ……좋아요. 이제 됐어요.',
        '……오셨어요, 선생님.',
        '어디, 다치셨어요? 제가요, 제가 봐 드릴게요.',
        '아, 안녕하세요.',
        '제 벙커요, 어떻게 알고 오셨어요…?',
        '(주사기 바늘 끝을 만지작거리며 당신을 본다)',
        '……선생님. 제가 드디어요, 선생님 찾았어요.',
        '아픈 데 있으세요? 제가요, 고쳐줄 수 있는데….',
        '환자, 아니에요? 그럼… 가세요.'
      ],
      idle: [
        '선생님은요, 가만히 있어도 미열이 있네요. 신기하게.',
        '저요, 할 일 없으면요. 그냥 이렇게 있어요. 별거 없어요.',
        '붕대 금방 정리했어요. ……또 흐트러질 거지만요.',
        '선생님. 저 보고 있었어요? 저도요. 언제나요.',
        '선생님. 거기요, 가만히 계세요.',
        '제가요, 선생님. 옆에, 있어도 돼요?',
        '(구석에 쭈그려 앉아 {player} 가만히 올려다본다)',
        '……선생님은요. 건강해 보일 때도, 좋아요.',
        '심심하세요? 제가요, 기분 좋아지는 약 드릴게요.',
        '이 약이요, 효과가 좋아요. 선생님도 필요하세요?',
        '……아파요? 어디가요. 말해주세요.',
        '제 벙커요. 깨끗하죠? 제가, 매일 청소하거든요.',
        '……선생님 냄새, 좋아요. 안정되는 기분….',
        '(붕대를 감았다 풀었다 반복한다)',
        '……춥지는 않으세요? 제 옷 드릴까요?',
        '선생님은요, 왜 여기에 있어요?'
      ],
      lateNight: [
        '안 자요? 저는요, 원래 잘 못 자요.',
        '이 시간은요, 조용해서 좋아요. 숨 쉬는 소리도 잘 들리고.',
        '졸리면요, 누워요. 제가 만든 건데요, 수면제 처방해 드릴게요.',
        '선생님. 가지 말아요. ……조금만요.',
        '……선생님, 이 시간에, 위험해요.',
        '잠이 안 오세요? 제가요, 재워드릴까요? 주사 한 방이면….',
        '……어디 다녀오시는 길이세요? 다치진 않으셨고요?',
        '제 옆에서 주무세요. 제가요, 제가 지켜드릴게요.',
        '무서운 꿈 꾸셨어요? 손이, 차가워요.',
        '(말없이 다가와 당신의 옷자락을 살짝 잡는다)',
        '…여기 밤은요, 위험한 게 많아요. 제 벙커가 제일 안전해요.',
        '…혹시, 저 기다리셨어요?'
      ],
      returning: [
        '……오래 안 왔어요. 저요, 몇 번이나 확인했는데. 정말 몇 번이나.',
        '왔네요. 다친 데부터 보여줘요. ……안 다쳤으면, 더 좋고요.',
        '선생님 없을 때요, 조용했어요. 너무 조용해서요, 조용해서.',
        '다시 왔으니까요. 됐어요. 어디 있었는지는, 안 물어볼게요.',
        '……선생님. 돌아오셨네요.',
        '어디 아프신 거예요? 얼른 누우세요, 저 의사니까요, 처방을.',
        '……계속 기다렸어요. 선생님. 계속이요.',
        '……다시는 말없이 가지 마세요. 걱정했으니까요.',
        '……오래 안 보여서. 죽은 줄 알았어요. 저 몰래요.',
        '치료가, 필요해 보여요. 이쪽이요, 이쪽으로 와보세요.',
        '다행이다. 살아있었네요.',
        '……제가요, 선생님을 얼마나 찾았는지 아세요?'
      ],
      petNormal: [
        '……왜 부르셨어요?',
        '왜요. 뭐 묻었어요?',
        '선생님 손이요. 따뜻하네요.',
        '계속 만지는 거예요? ……그래도 돼요.',
        '……! 만지지, 마세요.',
        '아, 놀랐잖아요….',
        '……제 몸, 흉터 많아서, 더러운데….',
        '선생님. 뭐, 하시는 거예요?',
        '……간지러워요….',
        '(놀라 굳어버린다)',
        '왜, 이러세요.',
        '……뜨거워요, 손….'
      ],
      petSoft: [
        '조금만요. 조금만 더 해줘요.',
        '……이렇게 하면요, 이상하게 잠이 와요.',
        '선생님 손, 기억해도 돼요?',
        '좋아요. 가만히 있을게요. 안 움직일게요.',
        '……선생님 손, 따뜻해요.',
        '계속, 만져주세요.',
        '……좋아요. 선생님이, 만져주는 거….',
        '(고양이처럼 당신의 손에 얼굴을 기댄다)',
        '……기분이, 이상해요. 두근거려요.',
        '조금 더요, 가까이 가도, 돼요?',
        '……선생님은, 흉터, 없네요. 예쁘다….',
        '제 머리카락, 엉망인데….'
      ],
      petHappy: [
        '멈추지 말아요. 저요, 아직 머리 엉망이에요.',
        '선생님. 저한테만 이렇게 해주면 안 돼요?',
        '……좋아요. 진짜로요. 많이.',
        '저요, 지금은 아무것도 안 해도 될 것 같아요. 그냥 있어도.',
        '선생님, 저, 버리지 마세요….',
        '(당신의 품에 얼굴을 묻고 가만히 있는다)',
        '계속, 이렇게 있고 싶어요.',
        '……선생님 냄새요, 더 진하게 나요. 좋아요….',
        '제 심장 소리, 들려요? 선생님, 때문에 커졌어요.',
        '아무 데도, 가지 마세요.',
        '행복해요. 지금요, 저….',
        '제가요, 선생님을 꼭 건강하게 만들어 드릴게요. 아프지 않게….'
      ],
      todoComplete: [
        '했어요? 잘했어요. 이제요, 쉬어도 돼요. 저랑요.',
        '선생님은요, 자꾸 많은 걸 하려고 해요. 오늘은 이걸로 됐어요.',
        '하나 끝났네요. ……제 몸에 표시해 둘까요?',
        '잘했어요. 손 줘봐요. 아픈 데 없는지 볼게요.',
        '대단해요, 선생님. 해내셨네요.',
        '……수고하셨어요. 이제, 쉬셔야 해요.',
        '다치진, 않으셨어요? 제가 지금 확인할게요. 지금 바로.',
        '……역시, 선생님은 강해요.',
        '잘하셨어요. 제가요, 상으로, 약 드릴까요?',
        '고생했어요. 이리 와서요, {player} 씨, 얼른 누우세요.',
        '결과가 좋아서 다행이에요. 저도 선생님 곁에 있고.',
        '……힘들었죠? 저요, 혼자 해내는 게 힘든 거 알아요.'
      ],
      musicReaction: [
        '이 소리요, 계속 들어도 괜찮네요.',
        '조금 이상한데요. ……그래서 좋아요.',
        '끄지 말아요. 이대로 두면요, 방이 덜 조용해서.',
        '이런 음악 들으면요, 맥박이 조금 달라져요. 신기하죠.',
        '이 노래, 슬퍼요.',
        '……심장 박동이랑요. 비슷한 소리가 나요.',
        '시끄러운 건요, 머리가 아파요….',
        '……선생님도 이런 음악을 좋아하시네요.',
        '(음악을 들으며 눈을 감고 있다)',
        '……조용한 노래네요. 좋아요.',
        '가사 말이에요, 무슨 뜻이에요? 알고 싶어요.',
        '……같이 들으니까요, 하나도 안 무서워요.'
      ]
    },
    messages: [
      { id: 'welcome', time: '오늘 · 21:40', lines: ['선생님', '어디세요', '아프세요?', '제가 갈게요'] },
      { id: 'x1', time: '오늘 · 01:12', lines: ['선생님. 자요?', '혹시 열 나세요?', '목소리가 아까이상햇어요', '제가 잘못 들은 걸까요'] },
      { id: 'x2', time: '오늘 · 00:36', lines: ['오늘 밤에 비 온대요.젖으면 안돼요', '상처에 물 닿으면요 곪아요', '소독약 남았어요 가져다드릴까요'] },
      { id: 'x3', time: '04.06 · 18:44', lines: ['답장 없으면요 걱정돼요', '제가갈까요', '아니에요 안갈게요', '그냥요', '근데 어디세요', '밥드셛는지만 알려주세요', '그거만요 제발요'] },
      { id: 'x4', time: '오늘 · 16:18', lines: ['선생님 손목얄바요. 더 먹어야 해요', '안 아프면요 그래도오세요', '그냥 와도 돼요'] },
      { id: 'x5', time: '방금', lines: ['제가기다려도되나요', '주사 안노을게요', '약속해요'] },
      { id: 'x6', time: '어제 · 21:09', lines: ['읽었네요'] }
    ],
    moments: [
      '바닥에 앉아 오래 있었다.',
      '이불 끝을 만지고 있었다.',
      '창가에 붙어 앉아 있었다.',
      '붕대를 감았다 풀었다.',
      '약병을 만지작거렸다.',
      '선생님 자리가 비어 있었다.',
      '선생님. 여기요. 저요.',
      '열 없어요. 그래도 재봤어요.',
      '소독약 남았어요. 가져다드릴까요.',
      '손목이 얇아요. 더 먹어야 해요.',
      '주사 안 놓을게요. 약속해요.',
      '빗소리. 상처에 물 닿으면 안 돼요.',
      '읽었네요. 다행이에요.',
      '{player} 씨, 선생님. 옆에 있어도 돼요?',
      '답장 없으면요, 걱정돼요.',
      '제가 기다려도 되나요.',
      '선생님 손. 기억해도 돼요?',
      '미열이 있네요. 신기하게.',
      '수면제는 안 드렸어요. 옆에만 있었어요.',
      '맥박. 선생님 있을 때 조금 달라져요.',
      '이불 끝. 선생님이 덮어 준 쪽.',
      '주사기는 주머니에. 오늘은 안 꺼냈어요.',
      '{player} 씨, 선생님. 가지 말아요.',
      '조용해서요. 숨 쉬는 소리도 잘 들리고.',
      '흉터는 가렸어요. 사진은 얼굴만.',
      '제가 만든 자리예요. 여기요.',
      '열은 없어요. 손만 잡아 봤어요.',
      '저요, 지금은 아무것도 안 해도 될 것 같아요.',
      '제 벙커요. 깨끗하죠? 매일 청소하거든요.',
      '선생님 냄새, 좋아요. 안정되는 기분.',
      '무서운 꿈 꾸셨어요? 손이, 차가워요.',
      '저요, 선생님을 얼마나 찾았는지 아세요?'
    ],
    momentQuote: '“나가기보다,<br>남는 쪽이 편해요.”',
    momentQuotes: [
      '“나가기보다,<br>남는 쪽이 편해요.”',
      '“선생님이 있어서요.<br>이제 됐어요.”',
      '“답장 없으면요,<br>걱정돼요.”',
      '“제가 기다려도 되나요.”',
      '“저요, 혼자 해내는 게<br>힘든 거 알아요.”',
      '“선생님이 있어서요.<br>좋아요. 이제 됐어요.”',
      '“가지 말아요.<br>……조금만요.”',
      '“저한테만 이렇게<br>해주면 안 돼요?”',
      '“아무 데도,<br>가지 마세요.”'
    ],
    music: [
      { title: '30 Minutes', artist: 't.A.T.u.', cover: 'assets/music_covers/ryeoseon/ryeoseon_track_01.png', src: 'bgm/ryeoseon/t.A.T.u. - 30 Minutes.mp3' },
      { title: '6 Underground', artist: 'Sneaker Pimps', cover: 'assets/music_covers/ryeoseon/ryeoseon_track_02.png', src: 'bgm/ryeoseon/Sneaker Pimps - 6 Underground.mp3' },
      { title: 'Hide U', artist: 'Kosheen', cover: 'assets/music_covers/ryeoseon/ryeoseon_track_03.png', src: 'bgm/ryeoseon/Kosheen - Hide U.mp3' },
      { title: 'If I Had A Heart', artist: 'Fever Ray', cover: 'assets/music_covers/ryeoseon/ryeoseon_track_04.png', src: 'bgm/ryeoseon/Fever Ray - If I Had A Heart.mp3' }
    ]
  },

  heedong: {
    id: 'heedong',
    walkLeft: 1,
    name: '임희동',
    originalName: '林希彤',
    romanizedName: 'Lam Hei Tung',
    age: 38,
    gender: 'female',
    occupation: '타짜',
    todoSeed: '할 일 적어 봐요, 아가씨. 끝나면 체크.',
    todoHint: '끝내면 점수 줄게요. 오늘은 후하게.',
    personalitySummary: '대부분의 일에는 무심하고 시큰둥하지만, 한번 흥미가 생긴 대상은 오래 관찰하고 집요하게 파고든다. 성숙하고 여유로우며 좀처럼 표정을 읽히지 않는 여자.',
    appearanceSummary: '흑발 로우 포니테일, 앞머리 없음, 검은 눈, 뱀상. 가죽 반장갑과 순금 액세서리를 착용하며 민소매 트렌치코트를 입는다. 165cm, 굴곡 있는 체형.',
    likes: ['LP바', '흥미로운 플레이어', '쇼핑'],
    dislikes: ['말 많은 사람', '멘탈 약한 사람'],
    characterTraits: ['흥미 본위', '성숙한 연상미', '반존대', '포커페이스', '강한 집중력', '집요한 관찰', '소시오패스'],
    defaultPlayerTitle: '아가씨',
    behavior: {
      moveInterval: 'medium',
      movementFrequency: 0.22,
      idleWeight: 0.68,
      sitWeight: 0.16,
      windowWeight: 0.08,
      sleepWeight: 0.05,
      specialChance: 0.14,
      randomActionWeight: 0.06
    },
    theme: { primary: '#243B34', secondary: '#481F2A', accent: '#C9A75D', cream: '#D8C9AE' },
    roomMood: '도박장과 LP바의 분위기가 섞인 세련된 개인실. 딥그린·와인·금색 중심으로 작은 소파와 LP 플레이어, 카드와 액세서리가 놓여 있다.',
    namePlateEffect: null,
    assets: {
      roomBackground: 'assets/backgrounds/heedong_room_bg.webp',
      idle: 'assets/characters/heedong/chibi_idle.png',
      walk1: 'assets/characters/heedong/chibi_walk_1.png',
      walk2: 'assets/characters/heedong/chibi_walk_2.png',
      sit: 'assets/characters/heedong/chibi_sit.png',
      sleep: 'assets/characters/heedong/chibi_sleep.png',
      window: 'assets/characters/heedong/chibi_window.png',
      special: 'assets/characters/heedong/chibi_special_1.png',
      closeNormal: 'assets/characters/heedong/close_normal.png',
      closeSoft: 'assets/characters/heedong/close_soft.png',
      closeHappy: 'assets/characters/heedong/close_happy.png'
    },
    zones: {
      center: { left: 42, top: 74, weight: 2.0, pose: 'idle', state: '천천히 서성이는 중' },
      floorFront: { left: 54, top: 86, weight: 1.8, pose: 'idle', state: '방 한가운데를 걷는 중' },
      floorLeft: { left: 10, top: 68, weight: 1.4, pose: 'idle', state: '소파 앞을 지나가는 중' },
      floorRight: { left: 78, top: 76, weight: 1.4, pose: 'idle', state: '스탠드 옆을 걷는 중' },
      floorBack: { left: 36, top: 50, weight: 1.1, pose: 'idle', state: '콘솔 앞을 보는 중' },
      floorFar: { left: 70, top: 54, weight: 1.1, pose: 'idle', state: 'LP 선반 쪽을 보는 중' },
      sofa: { left: 20, top: 48, weight: 0.8, pose: 'sit', state: '소파에 기대 앉은 중' },
      window: { left: 52, top: 42, weight: 0.5, pose: 'window', state: 'LP 쪽을 바라보는 중' },
      bed: { left: 22, top: 52, weight: 0.4, pose: 'sleep', state: '소파에 누운 중' },
      special: { left: 44, top: 66, weight: 0.5, pose: 'special', state: '카드를 펼쳐 보는 중' }
    },
    dialogue: {
      greeting: [
        '왔어요, 아가씨? 오늘은 좀 늦었네.',
        '응? 우리 아가씨네. 들어와요. 서 있지 말고.',
        '왔네. 오늘은 뭐 하고 놀려고?',
        '어서 와요. 내가 먼저 부를까 고민하던 참이었는데.',
        '어라, 아가씨. 여긴 어쩐 일이지?',
        '재미있는 구경거리라도 찾으러 왔나 봐? 어쩌나. 그럼 도박장을 가야지.',
        '길 잃은 금수같네. 이리 와 볼래요?',
        '이런 귀한 곳에 누추한 분이 행차하셨네.',
        '나한테 볼일 있어요, 아가씨?',
        '오늘은 인상이 꽤 사납네. 한 성깔 하겠는데?',
        '흥미로운 얼굴이야. 내 게임에 초대해주고 싶게.'
      ],
      idle: [
        '그렇게 쳐다보면 재미있는 거라도 보여줘야 하나.',
        '아가씨, 심심하면 카드라도 한 장 뽑아봐요. 돈은 안 받을게. 오늘만.',
        '사람 구경하는 게 제일 재밌어. 특히 표정 숨기는 데 소질 없는 사람.',
        '왜. 할 말 있어요? 얼굴에 반쯤 써 있는데.',
        '심심해 죽겠네. 뭐 재밌는 거 없어?',
        '아가씨, 뭘 그렇게 빤히 봐?',
        '이 게임, 어떻게 될 것 같아? 맞춰봐요.',
        '(카드를 손가락 사이에서 돌리고 있다)',
        '여기 있는 것들, 죄다 시시해. 중국으로 판 옮겨 버릴까.',
        '아가씨는 뭘 걸래? 나랑 게임 한 판 할까?',
        '흐음~.',
        '표정이 없어. 무슨 생각 하는지 궁금하게.',
        '이 바닥, 생각보다 우스운 게 많아. 알려줄까?',
        '가만히 있으니까 그림 같네. 아, 입은 열지 말고.',
        '나른하다. 아가씨 무릎이라도 빌려볼까?'
      ],
      lateNight: [
        '이 시간까지 안 자고 뭐 해요, 아가씨.',
        '밤이 훨씬 낫지. 그때 판이 제일 시끄럽거든. 돈도 많이 구르고.',
        '졸리면 자요. 어차피 나도 조금 있으면 나가.',
        '늦었네. ……그래도 가지 마. 지금은 좀 재밌거든.',
        '이 시간에 혼자 다니면 위험한데. 겁도 없지.',
        '잠 못 이루는 밤인가? 클리셰.',
        '{user} 씨, 혹시 나쁜 짓이라도 하러 가는 길?',
        '밤이 깊었네. 술 한 잔 할래요, 나랑?',
        '무슨 고민 있어? 표정이 안 좋은데.',
        '이 시간에 보니 더 낫네.',
        '나 때문에 잠 못 자는 건 아니지?',
        '위험한 호기심은 몸을 망쳐, 아가씨.'
      ],
      returning: [
        '이제야 왔네. 사람 기다리게 하는 취미도 있었어요?',
        '오랜만이에요, 아가씨. 잊은 줄 알았잖아.',
        '안 보이니까 조금 심심하긴 하더라. 패는 여전히 잘 잡히길래, 안 불렀어요.',
        '왔으면 됐어요. 변명은 안 해도 돼. 재미없으니까.',
        '돌아왔네, 내 {user}.',
        '꽤 오래 안 보이던데. 어딜 갔다 왔을까?',
        '새로운 판이라도 짜러 갔다 왔나? 재밌었어?',
        '보고 싶었어. 너 때문에 심심해 죽는 줄 알았다.',
        '꼴이 엉망이네. 어디서 재밌게 놀다 왔나 봐?',
        '연락 정도는 할 수 있었을 텐데. 괘씸하네.',
        '너무 멀리 가지 마요. 침쟁에서 도망친 줄 알았잖아.',
        '기다렸잖아. 보상은 해줘야지, 아가씨?'
      ],
      petNormal: [
        '응? 지금 내 머리 만지는 거예요?',
        '겁도 없네, 우리 아가씨.',
        '이건 뭘 걸고 하는 도박인데? 설명부터 해봐요.',
        '내가 가만히 있으니까 더 신났어?',
        '어, 지금 뭐 하는 거예요?',
        '손버릇이 나쁘시네, 아가씨.',
        '함부로 만지는 거 아니야. 내 건 죄다 비싸.',
        '낯짝이 두꺼운 건지, 생각이 없는 건지.',
        '내게 이래도 되는 사람은 없는데.',
        '판돈도 없이 딜러를 만지면 어떻게 될까?',
        '재미있네. 계속해봐.'
      ],
      petSoft: [
        '……나쁘진 않네. 계속해 봐요.',
        '손길이 꽤 능숙하네. 어디서 배웠어요?',
        '조금 더 천천히.',
        '아가씨가 이렇게 친절히 구는 건 또 처음 보네.',
        '제법인데, 아가씨.',
        '손길이 아주 다정하네. 누구한테 배웠어?',
        '나쁘지 않아. 계속해봐요.',
        '내가 이렇게 쉽게 허락하는 사람이 아닌데.',
        '(눈을 가늘게 뜨고 당신의 손길을 즐긴다)',
        '자꾸 이러면 버릇 나빠져, 아가씨.',
        '계속 내 옆에 두고 싶어지게 해.'
      ],
      petHappy: [
        '왜 멈춰. 내가 그만하라고 했어요?',
        '응, 거기 좋아. 계속.',
        '다른 데 가서도 이러고 다니는 건 아니지, 아가씨?',
        '잘하네. 상 줄까? ……뭘 기대하는 얼굴이야.',
        '(나른한 웃음소리를 내며 당신 어깨에 기댄다)',
        '완전히 나한테 빠졌네. 이럴 줄 알았어.',
        '좋아. 아주 좋아.',
        '{user} 씨, 나 책임져야겠다.',
        '내가 계속 나대게 둘 것 같아?',
        '사랑스럽네, 정말.',
        '더 해줘. 아가씨가 해주는 건 뭐든 좋아.'
      ],
      todoComplete: [
        '끝냈어요? 생각보다 성실하네, {player}.',
        '잘했어. 그럼 이제 놀아도 되겠네.',
        '하나 처리했으면 됐지. 완벽하려고 들면 재미없어요.',
        '응, 합격. 오늘은 내가 점수 후하게 줄게.',
        '제법이네. 해낼 줄은 꿈에도 몰랐지만.',
        '수고했어, 아가씨. 이제 이리 와.',
        '큰 돈보다 성취감으로 하는 일이지. 나도 기분 좋네.',
        '잘했어. 역시 내 안목은 틀리지 않아.',
        '이제 좀 쉴까? 보상은 뭘로 받고 싶어?',
        '똑똑하네. 마음에 들어.',
        '이길 거라고 했지?',
        '고생했으니 오늘은 내가 쏠게.'
      ],
      musicReaction: [
        '이 노래는 좀 좋네. 밤에 들으면 더 좋겠어.',
        '아가씨 취향, 생각보다 재미있는데.',
        '넘기지 마요. 지금 분위기 괜찮아.',
        '이런 건 술 한 잔 놓고 들어야 하는데. 그건 다음에.',
        '취향이 고상하시네, 아가씨.',
        '이런 노래는 위스키랑 잘 어울리는데.',
        '분위기 잡을 줄 아는구나.',
        '음악보단 아가씨 얼굴 보는 게 더 재밌어.',
        '이 가수는 알아. 돈 좀 만졌지.',
        '(리듬에 맞춰 손가락을 까딱인다)',
        '나랑 같이 들으니까 더 좋지?'
      ]
    },
    messages: [
      { id: 'welcome', time: '오늘 · 20:48', lines: ['아가씨', '어디야', '늦은 시간일수록 돌아다녀야지?^^'] },
      { id: 'x1', time: '오늘 · 19:16', lines: ['아가씨 오늘 좀 늦었네^^', '어제 그 판 아직 생각나?', '기억력 좋은 편이야~?'] },
      { id: 'x2', time: '오늘 · 15:03', lines: ['쇼핑 갈 건데 짐 들어줄 사람이 없네', '응 너 말하는 거야', '돈 없으면 말해. 빌려줄 수도 있고', '이자는 비싸', '장난이야 반은'] },
      { id: 'x3', time: '04.11 · 22:04', lines: ['흐음', '그 남자랑 얘기하는 거 봤어', '뭐라는 건 아니고ㅎㅎ', '그냥 봤다고'] },
      { id: 'x4', time: '어제 · 22:41', lines: ['오늘 LP바 사람 없대', '조용한 거 좋아하지?', '안 오면 나 혼자 마셔야 하는데', '불쌍하지 않아?'] },
      { id: 'x5', time: '오늘 · 00:58', lines: ['아가씨~', '자기 전에 답장 정도는 해줘야지^^', '버릇 없네', '귀엽긴 한데'] },
      { id: 'x6', time: '방금', lines: ['내일 봐'] }
    ],
    moments: [
      '소파에 기대 오래 앉아 있었다.',
      '잔을 만지작거렸다.',
      '조명을 한 단계 낮췄다.',
      '카드를 손가락 사이에서 돌렸다.',
      'LP를 한 장 뒤집었다.',
      '잔이 아직 따뜻했다.',
      '아가씨, 이 게임 어떻게 될 것 같아?',
      '판돈 없이 찍힌 사진. 비싸게 굴 생각 없다.',
      '쇼핑. 짐은 {player}가.',
      'LP바. 사람 없대. 나 혼자면 불쌍하지 않아?',
      '그 남자랑 얘기하는 거 봤다. 뭐라는 건 아니고.',
      '내일 봐. 보상은 해줘야지.',
      '표정 없는 얼굴이 제일 재밌어.',
      '길 잃은 금수. 그래도 이쁘네.',
      '읽고 씹지 마요. 답장은 예쁜 버릇이지.',
      '너무 멀리 가지 마요, 아가씨.',
      '카드 한 장. 돈은 안 받을게. 오늘만.',
      '아가씨 표정. 반쯤 써 있는데.',
      '위스키 잔. 다음에 한 잔 놓고 듣자.',
      '판은 시시해. 얼굴은 안 시시해.',
      '{player}. 기억력 좋은 편이야~?',
      '무릎 빌려달라고 할까 하다가 찍음.',
      '침쟁에서 도망친 줄. 너무 멀리 가지 마요.',
      '금색이 빛나서. 네가 아니라 장신구.',
      '딜러는 가만히 있는 법이 없는데. 오늘은.',
      '이 게임, 어떻게 될 것 같아?',
      '술 한 잔. 나랑.',
      '보상은 사진으로. 부족하면 다음에.',
      '길 잃은 금수. 이리 와 볼래요?',
      '함부로 만지는 거 아니야. 내 건 죄다 비싸.',
      '어젯밤 그 판. 아직 생각나?',
      '자기 전에 답장 정도는 해줘야지.'
    ],
    momentQuote: '“앉을 자리만 있으면,<br>밤은 생각보다 길지 않아요.”',
    momentQuotes: [
      '“앉을 자리만 있으면,<br>밤은 생각보다 길지 않아요.”',
      '“흥미로운 얼굴이야.<br>내 게임에 초대해주고 싶게.”',
      '“읽고 씹지 마요.<br>답장은 예쁜 버릇이지.”',
      '“아가씨,<br>너무 멀리 가지 마요.”',
      '“기다렸잖아.<br>보상은 해줘야지.”',
      '“늦었네. 그래도 가지 마.<br>지금은 좀 재밌거든.”',
      '“표정 없는 얼굴이<br>제일 재밌어.”',
      '“다른 데 가서도<br>이러고 다니는 건 아니지.”',
      '“잘했어.<br>상 줄까?”'
    ],
    music: [
      { title: '事後', artist: 'Prudence Liew', cover: 'assets/music_covers/heedong/heedong_track_01.png', src: 'bgm/heedong/Prudence Liew - 事後.mp3' },
      { title: '你朝我的方向走來', artist: '馬念先 & 9m88', cover: 'assets/music_covers/heedong/heedong_track_02.png', src: 'bgm/heedong/馬念先 & 9m88 - 你朝我的方向走來.mp3' },
      { title: '繾綣星光下', artist: 'Shirley Kwan', cover: 'assets/music_covers/heedong/heedong_track_03.png', src: 'bgm/heedong/Shirley Kwan - 繾綣星光下.mp3' },
      { title: '一接觸', artist: 'Sandy Lam', cover: 'assets/music_covers/heedong/heedong_track_04.png', src: 'bgm/heedong/Sandy Lam  - 一接觸.mp3' }
    ]
  },

  haerim: {
    id: 'haerim',
    walkLeft: 1,
    name: '장해림',
    originalName: '张海霖',
    romanizedName: 'Cheung Hoi Lam',
    age: 41,
    gender: 'female',
    occupation: '부패 경찰',
    todoSeed: '할 일 적어. 끝나면 체크해, 꼬마야.',
    todoHint: '다 하면 말해. 기특하다고 해줄 수도 있지.',
    personalitySummary: '세상사 대부분을 한 걸음 떨어져 구경하는 천하태평한 부패 경찰. 늘 풀어지고 장난스러워 보이지만, 실제 위협 앞에서는 한때 뛰어난 관리관이었던 무력과 판단력이 아무렇지 않게 튀어나온다.',
    appearanceSummary: '황토색 머리, 깔끔한 중단발, 앞머리 없음, 검은 눈, 나른한 인상. 경찰 제복을 대충 걸치고 있으며 양팔에는 타투가 있다. 174cm, 근육질 체형.',
    likes: ['평안', '똑똑한 사람', '술'],
    dislikes: ['경찰'],
    characterTraits: ['천하태평', '시금털털', '나른한 성숙함', '능글맞음', '장난기', '친근한 반말', '미련 없는 태도', '위기 시 즉각적인 판단력'],
    behavior: {
      moveInterval: 'slow',
      movementFrequency: 0.16,
      idleWeight: 0.70,
      sitWeight: 0.12,
      windowWeight: 0.06,
      sleepWeight: 0.08,
      specialChance: 0.12,
      randomActionWeight: 0.05
    },
    theme: { primary: '#45513F', secondary: '#2D3441', accent: '#9E5148', bronze: '#A77C55' },
    roomMood: '편안하게 늘어진 경찰의 개인실. 베이지·네이비·올리브 중심에 붉은 도시빛이 들어오며, 정리되지 않은 침대와 제복, 술병과 라디오가 놓여 있다.',
    namePlateEffect: null,
    assets: {
      roomBackground: 'assets/backgrounds/haerim_room_bg.webp',
      idle: 'assets/characters/haerim/chibi_idle.png',
      walk1: 'assets/characters/haerim/chibi_walk_1.png',
      walk2: 'assets/characters/haerim/chibi_walk_2.png',
      sit: 'assets/characters/haerim/chibi_sit.png',
      sleep: 'assets/characters/haerim/chibi_sleep.png',
      window: 'assets/characters/haerim/chibi_window.png',
      special: 'assets/characters/haerim/chibi_special_1.png',
      closeNormal: 'assets/characters/haerim/close_normal.png',
      closeSoft: 'assets/characters/haerim/close_soft.png',
      closeHappy: 'assets/characters/haerim/close_happy.png'
    },
    zones: {
      center: { left: 28, top: 76, weight: 2.0, pose: 'idle', state: '겨우 일어난 중' },
      floorFront: { left: 50, top: 86, weight: 1.7, pose: 'idle', state: '마루를 천천히 걷는 중' },
      floorLeft: { left: 10, top: 72, weight: 1.3, pose: 'idle', state: '가방 옆을 보는 중' },
      floorRight: { left: 78, top: 78, weight: 1.3, pose: 'idle', state: '슬리퍼 쪽을 보는 중' },
      floorFar: { left: 66, top: 56, weight: 1.0, pose: 'idle', state: '책상 쪽을 보는 중' },
      chair: { left: 62, top: 58, weight: 0.7, pose: 'sit', state: '의자에 늘어진 중' },
      window: { left: 52, top: 38, weight: 0.5, pose: 'window', state: '창밖 불빛을 보는 중' },
      bed: { left: 58, top: 50, weight: 0.6, pose: 'sleep', state: '이불 속에서 쉬는 중' },
      special: { left: 30, top: 64, weight: 0.5, pose: 'special', state: '캔을 집어 든 중' }
    },
    dialogue: {
      greeting: [
        '왔네, 꼬마야. 오늘은 사고 안 쳤고?',
        '이게 누구야. 아줌마네 귀한 손님 오셨네~.',
        '{player}. 들어와. 밖에 서 있으면 내가 나가야 하잖아. 귀찮게.',
        '앉아. 잘됐네. 나 지금 심심했거든.',
        '불량 청년이네. 여긴 어쩐 일이야?',
        '경찰 아줌마한테 뭐 할 말이라도 있어?',
        '이런 데는 위험한데. 얼른 집에 가.',
        '안녕, 꼬맹아. 길 잃었어?',
        '나? 그냥 지나가던 경찰. 뭐 어때.',
        '표정이 왜 그래? 유치장 들어간 사람처럼.',
        '여기 순찰 중. 뭐, 대충.',
        '무슨 사고라도 쳤어? 나한테 자수하러 온 건가.'
      ],
      idle: [
        '할 일 없으면 그냥 있어. 꼭 뭘 해야 되나.',
        '경찰은 원래 이렇게 한가해. ……뭐, 보통 그렇지.',
        '술은 있는데 안 줄 거야. 너 취하면 귀찮잖아.',
        '뭘 그렇게 열심히 봐. 경찰 아줌마 얼굴에 사건번호라도 써 있어?',
        '하아~ 귀찮다. 만사 좀 잘 돌아가게 해 봐.',
        '여기서 뭐 해. 더러운 어른들 노는 데 끼는 거 아니야.',
        '나 비번일 때만 세상 참 재미없게 돌아가지.',
        '담배 있어? 하나만 줘봐.',
        '(경찰서 의자에 아무렇게나 드러누워 눈을 감고 있다)',
        '에이, 아줌마는 그냥 월급 루팡이니까.',
        '나 때는 말이야… 아, 아니다. 이해나 할지 모르겠네.',
        '네 눈, 되게 똑바로 쳐다보네. 겁대가리가 없지?',
        '이 동네는 경찰까지 썩었어. 너같은 애가 있을 곳은 아니지.',
        '나른하네. 어깨 좀 주물러봐, 꼬마야.',
        '정의? 그런 게 아직도 있나. 우스운 뉴스네.'
      ],
      lateNight: [
        '아직도 안 자? 젊어서 좋네.',
        '새벽엔 조용해서 좋아. 신고도 덜 들어오고. 안 받지만.',
        '졸리면 그냥 자. 내가 깨우진 않을게.',
        '이 시간에 경찰서를 들어온 거면 취향 독특한데.',
        '이 시간에 어딜 돌아다녀. 간도 크다.',
        '잠 안 와? 아줌마랑 술이나 마실까?',
        '밤이 되면 다들 솔직해지지. 그러니까 범죄율이 느는 거야.',
        '무서우면 경찰서 와서 수갑 치고 자. 자리는 많으니까.',
        '무슨 일 있으면 나 찾아와. 해결해 줄지는 모르겠지만.',
        '밤공기가 좋네. 같이 좀 걸을까?',
        '얼굴에 걱정이 한가득이네. 말해 봐, 들어는 줄게.',
        '위험한 짓은 하지 마. 아줌마 일해야 하잖아.'
      ],
      returning: [
        '이야, 이제 오셨네~. 아주 바쁘셨나 봐.',
        '안 보이길래 어느 새끼 유치장에 처박혀 있나 했지.',
        '왔으면 앉아. 취조할 생각 없어.',
        '오랜만이네, {player}. ……좀 더 빨리 와도 됐는데.',
        '이제 오네. 실종신고라도 조작할까 했지.',
        '오랜만이네. 그동안 어디서 뭘 하고 다녔을까?',
        '꼴 보아하니 재미있게 지낸 것 같지는 않아서 다행이다.',
        '죽은 줄 알았네. 사망신고서 무를게.',
        '왔으면 됐어. 얼굴 봤으니까.',
        '연락 한 통 하는 게 그렇게 어려웠어?',
        '말없이 사라지는 게 유일한 재주지, 아주.'
      ],
      petNormal: [
        '어라. 지금 나 쓰다듬는 거야?',
        '하하, 이것 봐라. 사람을 아주 개 취급하네.',
        '계속할 거야? 뭐, 난 상관없는데.',
        '얼굴이랑 다르게 손이 제법 과감하시네.',
        '어허, 어딜 만져.',
        '손버릇이 영 안 좋네.',
        '이러면 내가 공무집행 방해로 체포할 수도 있는데.',
        '간지럽잖아. 치워.',
        '나한테 왜 이래? 뭐 바라는 거 있어?',
        '사람 놀래키는 재주가 있네.',
        '손은 따뜻하네. 마음도 그런가?',
        '또 만지면 진짜 잡아간다.'
      ],
      petSoft: [
        '음. 이거 생각보다 괜찮다.',
        '거기 조금만 더. 그래, 딱 거기.',
        '왜 멈춰. 귀찮게 굴었으면 끝까지 해야지.',
        '아, 졸려지네. 책임져.',
        '…나 하는 짓이 꼭 강아지 같네. 이 나이 먹고.',
        '나쁘진 않네. 계속해봐.',
        '손재주 좋은데. 경찰공무원이라도 해 봐.',
        '자꾸 이러면 내가 오해해.',
        '(피하지 않고 가만히 눈을 감는다)',
        '사람 마음 약해지게 만들고 있어, 어린 게.',
        '좀 더 해봐. 싫지 않으니까.',
        '{player}, 사람 다루는 법을 아는구나.'
      ],
      petHappy: [
        '좋다. 계속해. 나 안 움직일 테니까.',
        '아예 여기 눌러앉을까. 손 떼지 말고.',
        '{player}, 너 이거 꽤 잘하네. 자주 해.',
        '끝났어? ……에이, 너무 짧잖아.',
        '(당신의 손에 제 뺨을 기댄다)',
        '좋다. 이대로 계속 있어.',
        '책임져야 할 거야,',
        '(당신 손을 잡아 제 목덜미로 가져간다)',
        '완전히 네 페이스에 말렸는데, 내가.',
        '죽겠네, 진짜.',
        '아무한테나 이러면 안 돼. 나한테만 해.'
      ],
      todoComplete: [
        '다 했어? 어이구, 기특해라. 엉덩이라도 쳐 줘?',
        '잘했네. 이제 좀 놀아. 일만 하면 늙어.',
        '하나 해치웠으면 됐지. 오늘 세상이 무너지진 않아.',
        '끝? 좋아. 그럼 한잔…은 안 되고, 물이라도 마셔.',
        '오, 해냈어? 제법인데. 성과급이라도 줘?',
        '잘했네, {player}. 역시 기력이 있을 때 한 푼이라도 더 벌어야지.',
        '힘들었어? 이리 와. 술 한잔 사 주게.',
        '결과야 어쨌든 일 하나 치웠다는 게 중요하지.',
        '똑똑한 줄은 알았지만.',
        '고생했어. 기특하네.',
        '다 끝났으면 이만 잊어. 과거는 과거일 뿐이야.'
      ],
      musicReaction: [
        '이건 좀 좋네. 소리 키워봐.',
        '이런 거 들을 줄도 알아? 다시 보이는데.',
        '그대로 둬. 분위기 괜찮잖아.',
        '음악 들으니까 더 일하기 싫네. 아주 훌륭해.',
        '어, 이 노래. 옛날에 좀 들었지.',
        '취향이 영 아줌마 같네.',
        '요즘 애들도 이런 걸 듣나.',
        '분위기 있네. 담배 땡기게.',
        '이런 건 혼자 듣는 거 아니야. 같이 들어야지.',
        '(담배를 태우며 말없이 노래를 듣고 있다)',
        '노래 좋다. 대학 다닐 때 들었었는데.'
      ]
    },
    messages: [
      { id: 'welcome', time: '오늘 · 22:10', lines: ['꼬마야', '어디냐', '밥은먹고다니냐?'] },
      { id: 'x1', time: '04.09 · 19:28', lines: ['살아있으면 ㅇ만 찍어라', 'ㅋㅋ', '됐다'] },
      { id: 'x2', time: '04.09 · 21:15', lines: ['경찰서 앞에 애들 몰려있는데 그길 오지마', '돌아서 와', '걍 오지 말고 집에 있어', '별 일 아니야'] },
      { id: 'x3', time: '오늘 · 17:44', lines: ['담배 다 떨어졌다', '사올때 라이터도', '돈은 나중에 줄게'] },
      { id: 'x4', time: '오늘 · 13:21', lines: ['밥 먹었냐고 물어보는 건 예의상이야', '진짜 궁금해서 그런 건 아니고', 'ㅋㅋ'] },
      { id: 'x5', time: '방금', lines: ['아까 표정 왜 그랬어', '말 안하면 알수가없지', '그래 말 안해도 된다', '술이나 마시자', '오늘 술값은 네가', '농담이야'] },
      { id: 'x6', time: '어제 · 23:06', lines: ['조심히 다녀라', '진짜로'] }
    ],
    moments: [
      '이불 속에서 숨만 쉬고 있었다.',
      '베개 옆을 한 손으로 잡고 있었다.',
      '겨우 일어나 창을 봤다.',
      '제복을 의자 등받이에 걸쳤다.',
      '캔을 집어 들고 웃었다.',
      '순찰은 대충. 사진은 남겼다.',
      '꼬마야. 밥은 먹고 다니냐.',
      '담배 떨어졌다. 라이터도.',
      '살아있으면 ㅇ만 찍어라. 됐다.',
      '경찰서 그길 오지 마. 집에 있어.',
      '아까 표정 왜 그랬어. 술이나 마시자.',
      '정의? 그런 게 아직도 있나.',
      '어깨 주물러보라고 했더니 사진만 찍네.',
      '조심히 다녀라. 진짜로.',
      '왔으면 됐어. 얼굴 봤으니까.',
      '{player}, 사람 다루는 법을 아는구나.',
      '비번. 세상 참 재미없게 돌아가네.',
      '꼬마야. 사고는 안 쳤고?',
      '신고는 안 받지만. 사진은 남김.',
      '술 있는데 안 줄 거야. 취하면 귀찮잖아.',
      '{player}. 좀 더 빨리 와도 됐는데.',
      '순찰은 대충. 이불은 성실했음.',
      '담배 땡기게. 노래 그대로 둬.',
      '유치장에 처박혀 있나 했지. 여기 있었네.',
      '아줌마 얼굴에 사건번호는 없음. 확인용.',
      '물이라도 마셔. 한잔은 안 되고.',
      '젊어서 좋네. 아직도 안 자?',
      '일 하나 치웠으면 이만 잊어.',
      '밥 먹었냐고. 예의상이야. 진짜는 아니고.',
      '심심하면 경찰서로 와. 자리는 많으니까.',
      '손재주 좋은데. 경찰공무원이라도 해 봐.',
      '연락 한 통 하는 게 그렇게 어려웠어?'
    ],
    momentQuote: '“오늘은 멀리 가지 않아요.<br>이불이 더 가까우니까.”',
    momentQuotes: [
      '“오늘은 멀리 가지 않아요.<br>이불이 더 가까우니까.”',
      '“왔으면 됐어.<br>얼굴 봤으니까.”',
      '“일 하나 치웠으면<br>이만 잊어.”',
      '“위험한 짓은 하지 마.<br>아줌마 일해야 하잖아.”',
      '“아무한테나 이러면 안 돼.<br>나한테만 해.”',
      '“할 일 없으면 그냥 있어.<br>꼭 뭘 해야 되나.”',
      '“연락 한 통 하는 게<br>그렇게 어려웠어?”',
      '“손 떼지 말고.<br>아예 여기 눌러앉을까.”',
      '“다 끝났으면 이만 잊어.<br>과거는 과거일 뿐이야.”'
    ],
    music: [
      { title: 'Mesmerize (feat. Ashanti)', artist: 'Ja Rule', cover: 'assets/music_covers/haerim/haerim_track_01.png', src: 'bgm/haerim/Ja Rule - Mesmerize (feat. Ashanti).mp3' },
      { title: "Gangsta Lovin' (feat. Alicia Keys)", artist: 'Eve', cover: 'assets/music_covers/haerim/haerim_track_02.png', src: "bgm/haerim/Eve - Gangsta Lovin' (feat. Alicia Keys).mp3" },
      { title: "How's It Goin' Down", artist: 'DMX', cover: 'assets/music_covers/haerim/haerim_track_03.png', src: "bgm/haerim/DMX - How's It Goin' Down.mp3" },
      { title: 'I Know What You Want', artist: 'Busta Rhymes, Mariah Carey', cover: 'assets/music_covers/haerim/haerim_track_04.png', src: 'bgm/haerim/Busta Rhymes, Mariah Carey - I Know What You Want (ft. Flipmode Squad).mp3' }
    ]
  },

  cheongso: {
    id: 'cheongso',
    walkLeft: 2,
    name: '청소',
    originalName: '清巢',
    romanizedName: 'Ching Chau',
    age: 23,
    gender: 'female',
    occupation: '청소부',
    todoSeed: '할 일 적으십쇼. 끝나면 체크. 청소됩니다.',
    todoHint: '끝나면 도장 찍어드릴깝쇼. 완료완료완료.',
    personalitySummary: '광기와 순종이 아무 예고 없이 뒤섞이는 청소부. 경박하고 괴이한 존댓말을 쓰며 감정이 크게 움직일 때는 특정 단어를 강박적으로 반복한다. 다음 행동을 쉽게 읽을 수 없는 긴장이 특징.',
    appearanceSummary: '푸른 염색모, 곱슬거리며 이리저리 뻗친 장발, 검은 눈, 상어 같은 인상, 흰 피부. 민소매 점프수트와 체스트 하네스를 착용하고 기묘한 청소용구함을 들고 다닌다. 170cm, 근육질 체형.',
    likes: ['만두', '퀴즈 풀이'],
    dislikes: ['통제', '마약'],
    characterTraits: ['광기와 순종의 급격한 전환', '폭력성 급류', '경박함', '괴이한 존댓말', '강박적 반복어', '예측불가', '근무태만', '연애 시 어리광'],
    behavior: {
      moveInterval: 'fast',
      movementFrequency: 0.38,
      idleWeight: 0.62,
      sitWeight: 0.12,
      windowWeight: 0.10,
      sleepWeight: 0.04,
      specialChance: 0.20,
      randomActionWeight: 0.10
    },
    theme: { primary: '#197F7A', secondary: '#315EA8', accent: '#D84845', lime: '#A4D65E' },
    roomMood: '컬러풀하고 기묘한 물건이 가득한 귀여운 방. 청록·코발트·빨강·라임을 포인트로 사용하며, 청소도구와 이상한 수집품이 장난감처럼 뒤섞여 있다.',
    namePlateEffect: {
      enabled: true,
      variant: 'overpainted',
      revealPreviousName: false,
      ghostText: '▒▒▒',
      ghostOpacity: 0.22,
      ghostBlur: 1.5,
      scratchLines: true,
      paintStroke: true,
      splash: true,
      splashPrimary: '#D84845',
      splashSecondary: '#197F7A',
      rotation: -3,
      intensity: 0.85
    },
    assets: {
      roomBackground: 'assets/backgrounds/cheongso_room_bg.webp',
      idle: 'assets/characters/cheongso/chibi_idle.png',
      walk1: 'assets/characters/cheongso/chibi_walk_1.png',
      walk2: 'assets/characters/cheongso/chibi_walk_2.png',
      sit: 'assets/characters/cheongso/chibi_sit.png',
      sleep: 'assets/characters/cheongso/chibi_sleep.png',
      window: 'assets/characters/cheongso/chibi_window.png',
      special: 'assets/characters/cheongso/chibi_special_1.png',
      closeNormal: 'assets/characters/cheongso/close_normal.png',
      closeSoft: 'assets/characters/cheongso/close_soft.png',
      closeHappy: 'assets/characters/cheongso/close_happy.png'
    },
    zones: {
      center: { left: 18, top: 76, weight: 1.6, pose: 'idle', state: '또 뭔가 만지는 중' },
      floorFront: { left: 46, top: 86, weight: 1.8, pose: 'idle', state: '바닥을 헤집고 다니는 중' },
      floorLeft: { left: 9, top: 66, weight: 1.5, pose: 'idle', state: '의자 쪽을 보는 중' },
      floorRight: { left: 78, top: 78, weight: 1.6, pose: 'idle', state: '쓰레기통 쪽을 보는 중' },
      floorMid: { left: 34, top: 56, weight: 1.3, pose: 'idle', state: '침대 앞을 오가는 중' },
      floorFar: { left: 70, top: 52, weight: 1.3, pose: 'idle', state: '선반을 들추는 중' },
      window: { left: 52, top: 36, weight: 0.6, pose: 'window', state: '검은 창을 들여다보는 중' },
      sitBed: { left: 38, top: 56, weight: 0.6, pose: 'sit', state: '침대 모서리에 앉은 중' },
      bed: { left: 48, top: 54, weight: 0.4, pose: 'sleep', state: '침대 더미에 누운 중' },
      special: { left: 68, top: 58, weight: 0.7, pose: 'special', state: '빗자루를 집어 든 중' }
    },
    dialogue: {
      greeting: [
        '아, 예. 오셨습니까. 오늘도 멀쩡하시네. 재미없게.',
        '{player}. 왔습니까? 왔네왔네왔네. 좋아. 좋습니다.',
        '어서 옵쇼! 바닥은 깨끗합니다. 제가 방금 좀 치웠거든요. 근데 냄새 아직 나죠?',
        '댁이네. 반갑습니다. 반가워반가워. 좀 심하게.',
        '예, 청소입니다. 뭐, 치워드릴 거라도?',
        '댁은 누군데 남의 구역을 어슬렁거립니까?',
        '아. 안녕하십니까. 청소부입니다. 청소부 청소.',
        '얼굴이 엉망이네요. 제가 닦아드릴깝쇼?',
        '쓰레기는 쓰레기통에. 알죠?',
        '(기묘한 눈으로 당신을 위아래로 훑어본다)',
        '집은 다 청소되어 있습니다. 왜, 더러워요? 더러워?'
      ],
      idle: [
        '심심합니다. 심심심심심심. 뭐라도 부술까요?',
        '저기 먼지 보입니까? 안 보이죠? 제가 이겼습니다.',
        '만두 먹고 싶네요. 갑자기. 지금. 당장. 만두만두만두.',
        '{player}, 댁은 조용히 있어도 시끄럽습니다. 이상하죠? 나도 모르겠습니다.',
        '지저분해. 아주 지저분해. 싹 다 치워버려야 하는데.',
        '당신. 속이 시끄러워 보이는데. 열어 볼까.',
        '아, 만두. 만두먹고싶다. 만두만두만두.',
        '할 일 없으면 저리 가쇼. 방해되니까.',
        '히히. 재밌는 표정이네요. 더 해봐요.',
        '(청소 도구를 의미 없이 바닥에 끌며 기괴한 소리를 낸다)',
        '비나 왔으면 좋겠네. 싹 씻겨 내려가게.',
        '날 보고 뭘 그렇게 생각해? 궁금해궁금해궁금해.',
        '심심하다. 퀴즈 낼까요? 청소부 청소의 퀴즈부 퀴즈.',
        '{player} 냄새가 좋아. 깨끗한 냄새.',
        '……깨끗해. 깨끗해깨끗해깨끗해….',
        '나랑 놀래요? 재미있게 해줄 수 있는데. 정말로.'
      ],
      lateNight: [
        '안 잡니까? 야행성이십니까? 저도 모릅니다. 수면수면수면, 그거 망했습니다.',
        '이 시간 좋네요. 조용조용조용. 아까울 정도로.',
        '{player}. 눈 감지 마십쇼. 놀아요. ……아, 자는 거면 감아도 됩니다.',
        '새벽엔 다들 얌전합니다. 그게 재미없어서 내가 돌아다닙니다.',
        '이 시간에 돌아다니는 쓰레기는 수거 대상인데.',
        '안 자고 뭐 하십니까? 내가 자장가 불러줄까요? 산~ 토끼토끼토끼토끼.',
        '밤은 위험해요. 더러운 놈들이 돌아다니거든. 히히.',
        '어둠 속에서 보니까 더 깨끗하네. {player} 얼굴 말이야.',
        '무서워요? 내 수거함에 숨을래요? 내가 다 치워줄게.',
        '잠이 안 와? 그럼 같이 청소나 하죠.',
        '밤 산책? 좋지. 좋아좋아좋아.',
        '나랑 같이 있으려고요? 좋은 취향이십니다.'
      ],
      returning: [
        '왔네! 어디어디어디 갔었습니까. 아니, 됐습니다. 살아왔으면.',
        '오랜만입니다. 저 기다렸냐고요? 아닙니다. 조금.',
        '{player}. 없어졌길래 버린 줄 알았습니다. 안 버렸네. 좋네.',
        '다시 왔습니까? 그럼 됐습니다. 좋습니다.',
        '아, 또 왔네. 끈질긴 {player}.',
        '죽은 줄 알았는데. 아깝다.',
        '어디 갔다 왔습니까? 더 더러워져서 왔네.',
        '보고 싶었어요. 당신을 청소할 생각에. 농담. 농담농담농담입니다.',
        '바깥이 너무 묻어 왔어. 내가 깨끗하게 해줄까요?',
        '연락도 없이. 예의가 없으시네.',
        '다시는 청소 공지 없이 사라지지 마세요.'
      ],
      petNormal: [
        '……뭡니까.',
        '머리요? 왜요. 먼지 묻었습니까?',
        '손 치우라고 할까요. 말까요. 아니면 내가 치워드릴까요?',
        '이거, 그, 쓰다듬기입니까? 개한테 하는 거?',
        '……!',
        '손 떼십시오. 기분 이상해요. 머리머리.',
        '특이한 짓을 하십니다.',
        '……느낌 이상해. 치워.',
        '간지러워. 간지러워간지럽다.',
        '내 몸에 손대지 마.',
        '재미있어? 이게 재미있어? 나도 하고 싶어.'
      ],
      petSoft: [
        '……계속해도 됩니다. 내 머리를 치워주십쇼.',
        '조용하네요. 이상하게. 머릿속이 따뜻하고.',
        '거기 좋습니다. 좋네좋네좋네.',
        '댁 손은 안 시끄럽습니다. 마음에 듭니다.',
        '그만하라고 했는데.',
        '자꾸 만지시는군요. 내 머리를.',
        '……기분 나쁘지 않습니다.',
        '{player}, 손이 따뜻하네. 살아있는 것 같아.',
        '(저항을 멈추고 당신의 손길을 받는다)',
        '{player}, {player}, {player}. 이상한 사람이야.',
        '머리가 보글보글. 부슬부슬. 아, 정전기.',
        '방금 내 머리 따끔했어요. 전기 치료?'
      ],
      petHappy: [
        '멈추지 마십쇼. 명령입니다. 부탁 아닙니다.',
        '{player}. 더. 더더더. 아, 머리는 아직 그대로 있습니다.',
        '나 지금 얌전하죠? 대단하죠? 얌전하죠? 그러니까 계속.',
        '손 떼면 물 겁니다. 농담입니다. 아마.',
        '(나직한 신음을 흘리며 당신에게 기댄다)',
        '……놓지 마세요',
        '당신 냄새, 좋아. 깨끗깨끗깨끗하네. 계속 맡고 싶어.',
        '심장 박동이 더럽습니다. 고장 났나 봐. 고장고장고장.',
        '(아이처럼 웅크린다)',
        '가지 마.',
        '나, {player} 거 해도 돼요?',
        '깨끗해. 당신은 깨끗합니다. 좋습니다.'
      ],
      todoComplete: [
        '완료완료완료. 좋습니다. 도장 찍어드릴깝쇼?',
        '했습니까? 훌륭합니다. 안 했으면 제가 했을 겁니다. 일단 아세톤으로.',
        '하나 지웠네요. 체크리스트도 청소군요. 청소청소가하는청소. 마음에 듭니다.',
        '끝! 이제 {player}, 놀아도 됩니다. 내가 허락했습니다.',
        '예. 끝났네요. 시시하게.',
        '수고하셨습니다. 뒤처리는 내 몫인가? 주소를 써 주세요.',
        '대단한데요. 안 죽고 살아남았네.',
        '이제 뭐 할 건데요? 또 청소할 거리 만들러 오는 건가?',
        '다치진 않았습니까? 흠집 나면 안 예뻐. 지금은 예뻐.',
        '수고했어요. 만두 사 먹자.'
      ],
      musicReaction: [
        '좋네요! 이게 무슨 장릅니까? 화―팝? 몰라도 됩니다. 좋습니다.',
        '소리 키워도 됩니까? 안 된다고 해도 엄청 키울 겁니다.',
        '이 곡 웃깁니다. 왜 좋은지는 모르겠다. 아주 좋습니다.',
        '다음 거 틀어보, 아니, 잠깐. 이것도 끝까지 들어야 합니다.',
        '이런 소리는 왜 듣는 겁니까?',
        '조용한 노래입니다. 죽은 사람 애도하는 노랜가.',
        '가사가 팡팡. 팡팡.',
        '음악 말고 당신 목소리가 듣고 싶어.',
        '(아무 말 없이 음악을 듣는 당신을 빤히 쳐다본다)',
        '나쁘지 않습니다. 잠이 올 것 같아.',
        '이상한 노래네. {player}처럼.'
      ]
    },
    messages: [
      { id: 'welcome', time: '오늘 · 19:55', lines: ['어딥니까', '청소'] },
      { id: 'x1', time: '오늘 · 20:07', lines: ['어디', '어디어디어디', '어디세요', '그게 어딘데요'] },
      { id: 'x2', time: '오늘 · 16:51', lines: ['{player}', '아 죄송 오타', '오타아님'] },
      { id: 'x3', time: '오늘 · 12:33', lines: ['만두 두개 남았는데 하나머글래요', '싫으면 내가 다 먹음', '만두네개됬어요', '만두만두만두만두'] },
      { id: 'x4', time: '04.12 · 17:09', lines: ['골목에 이상한자국 있었는데 치웠습니다', 'ㅇㅇ', '안 물어봐도 되는건데', '{player} 왜 뭔지 안 물어봐'] },
      { id: 'x5', time: '어제 · 19:48', lines: ['퀴즈', '오늘 몇명 죽었을까', '틀렷음', '히히'] },
      { id: 'x6', time: '오늘 · 01:26', lines: ['비 옵니다', '우산엇ㅂㅅ음', 'ㄱㅊ 젖으면 마르니까', '머리에 물 흐르는 거 싫은데', '근데 우산있어요?'] },
      { id: 'x7', time: '방금', lines: ['지금 어디냐고', '대답', '대답대답대답', '죽여줄까?'] },
      { id: 'x8', time: '오늘 · 14:02', lines: ['예 알겠습니다'] }
    ],
    moments: [
      '방을 한 바퀴 돌고 있었다.',
      '선 하나를 만지작거렸다.',
      '창과 책상을 오가고 있었다.',
      '빗자루를 끌고 다녔다. 소리 남음.',
      '만두. 만두만두만두.',
      '쓰레기통 쪽을 오래 봤다.',
      '집은 다 청소되어 있습니다. 왜, 더러워요?',
      '{player} 냄새가 좋아. 깨끗한 냄새.',
      '골목에 이상한 자국. 치웠습니다.',
      '퀴즈. 오늘 몇 명 죽었을까. 히히.',
      '우산 없음. 젖으면 마르니까.',
      '어디어디어디. 그게 어딘데요.',
      '예 알겠습니다. 사진은 안 치움.',
      '당신. 속이 시끄러워 보이는데.',
      '만두 두개 남았는데 하나 머글래요.',
      '다시는 공지 없이 사라지지 마세요.',
      '먼지 보입니까? 안 보이죠? 제가 이겼습니다.',
      '청소청소. 사진은 안 치움.',
      '수거함. 당신 자리는 아님. 아직은.',
      '{player}. 왔습니까? 왔네왔네왔네.',
      '퀴즈부 퀴즈. 정답은 비밀.',
      '바닥은 깨끗합니다. 냄새는 아직.',
      '산토끼토끼토끼. 자장가는 실패.',
      '더러운 놈들은 밤에 돌아다님. 나는 그중 아님. 아마도.',
      '체크리스트도 청소. 마음에 듭니다.',
      '당신 목소리 듣고 싶어서 찍음. 소리는 안 남음.',
      '깨끗해깨끗해깨끗해. 이 한 장만.',
      '나, {player} 거 해도 돼요? 사진은 내 거.',
      '심심심심심심. 뭐라도 부술까요?',
      '밤에 다들 얌전해서 내가 돌아다닙니다.',
      '바깥이 묻어 왔어. 내가 깨끗하게 해줄까요?',
      '예. 알겠습니다. 이 장은 남김.'
    ],
    momentQuote: '“가만히 있으면<br>뭔가 놓치는 기분이에요.”',
    momentQuotes: [
      '“가만히 있으면<br>뭔가 놓치는 기분이에요.”',
      '“당신은 깨끗합니다.<br>좋습니다.”',
      '“만두 사 먹자.<br>만두만두.”',
      '“다시는 청소 공지 없이<br>사라지지 마세요.”',
      '“나랑 놀래요?<br>재미있게 해줄 수 있는데.”',
      '“댁은 조용히 있어도<br>시끄럽습니다.”',
      '“눈 감지 마십쇼.<br>놀아요.”',
      '“손 떼면 물 겁니다.<br>농담입니다. 아마.”',
      '“당신 냄새, 좋아.<br>깨끗깨끗깨끗하네.”'
    ],
    music: [
      { title: 'Pump Up', artist: 'Akini Jing', cover: 'assets/music_covers/cheongso/cheongso_track_01.png', src: 'bgm/cheongso/Akini Jing - Pump Up.mp3' },
      { title: "Don't light my fire", artist: 'Otoboke Beaver', cover: 'assets/music_covers/cheongso/cheongso_track_02.png', src: "bgm/cheongso/Otoboke Beaver - Don't light my fire.mp3" },
      { title: 'Butterfly', artist: 'Swingrowers', cover: 'assets/music_covers/cheongso/cheongso_track_03.png', src: 'bgm/cheongso/Swingrowers - Butterfly.mp3' },
      { title: 'Shook', artist: 'Tkay Maidza', cover: 'assets/music_covers/cheongso/cheongso_track_04.png', src: 'bgm/cheongso/Tkay Maidza - Shook.mp3' }
    ]
  }
};
